#!/bin/sh

PROJECT_NAME="qp"
echo "PROJECT_NAME: "$PROJECT_NAME

LOGIN_SVR_NAME=$PROJECT_NAME"login"
echo "LOGIN_SVR_NAME: "$LOGIN_SVR_NAME

CLIENT_DIR_NAME=$PROJECT_NAME"client"
echo "CLIENT_DIR_NAME: "$CLIENT_DIR_NAME

SERVER_DIR_NAME=$PROJECT_NAME"server"
echo "SERVER_DIR_NAME: "$SERVER_DIR_NAME

SERVER_DIR_PATH="/root/"$SERVER_DIR_NAME
echo "SERVER_DIR_PATH: "$SERVER_DIR_PATH

GAME_DB_NAME=$PROJECT_NAME"game"
echo "GAME_DB_NAME: "$GAME_DB_NAME

DB_PASSWORD="ra6snlj4m7gu0y9d"
echo "DB_PASSWORD: "$DB_PASSWORD

