//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ActiveMainTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActiveMainTable")]
  public partial class ActiveMainTable : global::ProtoBuf.IExtensible
  {
    public ActiveMainTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _RedPointPath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RedPointPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RedPointPath
    {
      get { return _RedPointPath; }
      set { _RedPointPath = value; }
    }
    private string _RedPointLocalPath;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RedPointLocalPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RedPointLocalPath
    {
      get { return _RedPointLocalPath; }
      set { _RedPointLocalPath = value; }
    }
    private string _UpdateMainKeys;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"UpdateMainKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UpdateMainKeys
    {
      get { return _UpdateMainKeys; }
      set { _UpdateMainKeys = value; }
    }
    private string _TabInitDesc;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"TabInitDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TabInitDesc
    {
      get { return _TabInitDesc; }
      set { _TabInitDesc = value; }
    }
    private string _FrameTemplate;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"FrameTemplate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FrameTemplate
    {
      get { return _FrameTemplate; }
      set { _FrameTemplate = value; }
    }
    private string _PurDesc;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"PurDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PurDesc
    {
      get { return _PurDesc; }
      set { _PurDesc = value; }
    }
    private string _ParticularDesc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"ParticularDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ParticularDesc
    {
      get { return _ParticularDesc; }
      set { _ParticularDesc = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private string _prefabDesc;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"prefabDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string prefabDesc
    {
      get { return _prefabDesc; }
      set { _prefabDesc = value; }
    }
    private string _awardparent;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"awardparent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string awardparent
    {
      get { return _awardparent; }
      set { _awardparent = value; }
    }
    private string _templateName;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"templateName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string templateName
    {
      get { return _templateName; }
      set { _templateName = value; }
    }
    private int _bUseTemplate;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"bUseTemplate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int bUseTemplate
    {
      get { return _bUseTemplate; }
      set { _bUseTemplate = value; }
    }
    private string _MainStatusDesc;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"MainStatusDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MainStatusDesc
    {
      get { return _MainStatusDesc; }
      set { _MainStatusDesc = value; }
    }
    private string _PrefabStatusDesc;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"PrefabStatusDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PrefabStatusDesc
    {
      get { return _PrefabStatusDesc; }
      set { _PrefabStatusDesc = value; }
    }
    private string _MainInitDesc;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"MainInitDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MainInitDesc
    {
      get { return _MainInitDesc; }
      set { _MainInitDesc = value; }
    }
    private string _FunctionParse;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"FunctionParse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FunctionParse
    {
      get { return _FunctionParse; }
      set { _FunctionParse = value; }
    }
    private string _ActiveFrame;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"ActiveFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActiveFrame
    {
      get { return _ActiveFrame; }
      set { _ActiveFrame = value; }
    }
    private string _ActiveFrameTabPath;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"ActiveFrameTabPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActiveFrameTabPath
    {
      get { return _ActiveFrameTabPath; }
      set { _ActiveFrameTabPath = value; }
    }
    private int _ActiveTypeID;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"ActiveTypeID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ActiveTypeID
    {
      get { return _ActiveTypeID; }
      set { _ActiveTypeID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}