//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuffTable.proto
// Note: requires additional types generated from: Union.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuffTable")]
  public partial class BuffTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public BuffTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Description;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _WorkType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"WorkType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WorkType
    {
      get { return _WorkType; }
      set { _WorkType = value; }
    }
    private int _DispelType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"DispelType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DispelType
    {
      get { return _DispelType; }
      set { _DispelType = value; }
    }
    private int _IsQuickPressSupport;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"IsQuickPressSupport", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsQuickPressSupport
    {
      get { return _IsQuickPressSupport; }
      set { _IsQuickPressSupport = value; }
    }
    private string _EffectShaderName;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"EffectShaderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EffectShaderName
    {
      get { return _EffectShaderName; }
      set { _EffectShaderName = value; }
    }
    private string _HeadName;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"HeadName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HeadName
    {
      get { return _HeadName; }
      set { _HeadName = value; }
    }
    private bool _IsShowSpell;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"IsShowSpell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsShowSpell
    {
      get { return _IsShowSpell; }
      set { _IsShowSpell = value; }
    }
    private string _BirthEffect;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"BirthEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BirthEffect
    {
      get { return _BirthEffect; }
      set { _BirthEffect = value; }
    }
    private string _BirthEffectLocate;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"BirthEffectLocate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BirthEffectLocate
    {
      get { return _BirthEffectLocate; }
      set { _BirthEffectLocate = value; }
    }
    private string _EffectName;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"EffectName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EffectName
    {
      get { return _EffectName; }
      set { _EffectName = value; }
    }
    private string _EffectLocateName;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"EffectLocateName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EffectLocateName
    {
      get { return _EffectLocateName; }
      set { _EffectLocateName = value; }
    }
    private bool _EffectLoop;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"EffectLoop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool EffectLoop
    {
      get { return _EffectLoop; }
      set { _EffectLoop = value; }
    }
    private string _EndEffect;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"EndEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EndEffect
    {
      get { return _EndEffect; }
      set { _EndEffect = value; }
    }
    private string _EndEffectLocate;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"EndEffectLocate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EndEffectLocate
    {
      get { return _EndEffectLocate; }
      set { _EndEffectLocate = value; }
    }
    private string _EffectConfigPath;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"EffectConfigPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EffectConfigPath
    {
      get { return _EffectConfigPath; }
      set { _EffectConfigPath = value; }
    }
    private string _HurtEffectName;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"HurtEffectName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HurtEffectName
    {
      get { return _HurtEffectName; }
      set { _HurtEffectName = value; }
    }
    private string _HurtEffectLocateName;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"HurtEffectLocateName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HurtEffectLocateName
    {
      get { return _HurtEffectLocateName; }
      set { _HurtEffectLocateName = value; }
    }
    private string _BuffAIPath;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"BuffAIPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BuffAIPath
    {
      get { return _BuffAIPath; }
      set { _BuffAIPath = value; }
    }
    private int _TargetState;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"TargetState", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TargetState
    {
      get { return _TargetState; }
      set { _TargetState = value; }
    }
    private int _Overlay;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"Overlay", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Overlay
    {
      get { return _Overlay; }
      set { _Overlay = value; }
    }
    private int _OverlayLimit;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"OverlayLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int OverlayLimit
    {
      get { return _OverlayLimit; }
      set { _OverlayLimit = value; }
    }
    private int _TriggerInterval;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"TriggerInterval", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TriggerInterval
    {
      get { return _TriggerInterval; }
      set { _TriggerInterval = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _StateChange = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(27, Name=@"StateChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> StateChange
    {
      get { return _StateChange; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AbilityChange = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(28, Name=@"AbilityChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AbilityChange
    {
      get { return _AbilityChange; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _UseSkillIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(29, Name=@"UseSkillIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> UseSkillIDs
    {
      get { return _UseSkillIDs; }
    }
  
    private int _DispelBuffType;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"DispelBuffType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DispelBuffType
    {
      get { return _DispelBuffType; }
      set { _DispelBuffType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _TriggerBuffInfoIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(31, Name=@"TriggerBuffInfoIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> TriggerBuffInfoIDs
    {
      get { return _TriggerBuffInfoIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MechanismID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(32, Name=@"MechanismID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MechanismID
    {
      get { return _MechanismID; }
    }
  
    private ProtoTable.UnionCell _hp;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private ProtoTable.UnionCell _mp;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private ProtoTable.UnionCell _hpRate;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"hpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell hpRate
    {
      get { return _hpRate; }
      set { _hpRate = value; }
    }
    private ProtoTable.UnionCell _mpRate;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"mpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell mpRate
    {
      get { return _mpRate; }
      set { _mpRate = value; }
    }
    private ProtoTable.UnionCell _currentHpRate;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"currentHpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell currentHpRate
    {
      get { return _currentHpRate; }
      set { _currentHpRate = value; }
    }
    private ProtoTable.UnionCell _baseAtk;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"baseAtk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell baseAtk
    {
      get { return _baseAtk; }
      set { _baseAtk = value; }
    }
    private ProtoTable.UnionCell _baseInt;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"baseInt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell baseInt
    {
      get { return _baseInt; }
      set { _baseInt = value; }
    }
    private ProtoTable.UnionCell _sta;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"sta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell sta
    {
      get { return _sta; }
      set { _sta = value; }
    }
    private ProtoTable.UnionCell _spr;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"spr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell spr
    {
      get { return _spr; }
      set { _spr = value; }
    }
    private ProtoTable.UnionCell _atkAddRate;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"atkAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell atkAddRate
    {
      get { return _atkAddRate; }
      set { _atkAddRate = value; }
    }
    private ProtoTable.UnionCell _intAddRate;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"intAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell intAddRate
    {
      get { return _intAddRate; }
      set { _intAddRate = value; }
    }
    private ProtoTable.UnionCell _staAddRate;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"staAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell staAddRate
    {
      get { return _staAddRate; }
      set { _staAddRate = value; }
    }
    private ProtoTable.UnionCell _sprAddRate;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"sprAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell sprAddRate
    {
      get { return _sprAddRate; }
      set { _sprAddRate = value; }
    }
    private ProtoTable.UnionCell _maxHp;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private ProtoTable.UnionCell _maxMp;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"maxMp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell maxMp
    {
      get { return _maxMp; }
      set { _maxMp = value; }
    }
    private ProtoTable.UnionCell _maxHpAddRate;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"maxHpAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell maxHpAddRate
    {
      get { return _maxHpAddRate; }
      set { _maxHpAddRate = value; }
    }
    private ProtoTable.UnionCell _maxMpAddRate;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"maxMpAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell maxMpAddRate
    {
      get { return _maxMpAddRate; }
      set { _maxMpAddRate = value; }
    }
    private ProtoTable.UnionCell _hpRecover;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"hpRecover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell hpRecover
    {
      get { return _hpRecover; }
      set { _hpRecover = value; }
    }
    private ProtoTable.UnionCell _mpRecover;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"mpRecover", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell mpRecover
    {
      get { return _mpRecover; }
      set { _mpRecover = value; }
    }
    private ProtoTable.UnionCell _attack;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private ProtoTable.UnionCell _magicAttack;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"magicAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell magicAttack
    {
      get { return _magicAttack; }
      set { _magicAttack = value; }
    }
    private ProtoTable.UnionCell _defence;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private ProtoTable.UnionCell _magicDefence;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"magicDefence", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell magicDefence
    {
      get { return _magicDefence; }
      set { _magicDefence = value; }
    }
    private ProtoTable.UnionCell _attackSpeed;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"attackSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell attackSpeed
    {
      get { return _attackSpeed; }
      set { _attackSpeed = value; }
    }
    private ProtoTable.UnionCell _spellSpeed;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"spellSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell spellSpeed
    {
      get { return _spellSpeed; }
      set { _spellSpeed = value; }
    }
    private ProtoTable.UnionCell _moveSpeed;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private ProtoTable.UnionCell _ciriticalAttack;
    [global::ProtoBuf.ProtoMember(59, IsRequired = true, Name=@"ciriticalAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ciriticalAttack
    {
      get { return _ciriticalAttack; }
      set { _ciriticalAttack = value; }
    }
    private ProtoTable.UnionCell _ciriticalMagicAttack;
    [global::ProtoBuf.ProtoMember(60, IsRequired = true, Name=@"ciriticalMagicAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ciriticalMagicAttack
    {
      get { return _ciriticalMagicAttack; }
      set { _ciriticalMagicAttack = value; }
    }
    private ProtoTable.UnionCell _dex;
    [global::ProtoBuf.ProtoMember(61, IsRequired = true, Name=@"dex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell dex
    {
      get { return _dex; }
      set { _dex = value; }
    }
    private ProtoTable.UnionCell _dodge;
    [global::ProtoBuf.ProtoMember(62, IsRequired = true, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private ProtoTable.UnionCell _frozen;
    [global::ProtoBuf.ProtoMember(63, IsRequired = true, Name=@"frozen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell frozen
    {
      get { return _frozen; }
      set { _frozen = value; }
    }
    private ProtoTable.UnionCell _hard;
    [global::ProtoBuf.ProtoMember(64, IsRequired = true, Name=@"hard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell hard
    {
      get { return _hard; }
      set { _hard = value; }
    }
    private ProtoTable.UnionCell _abnormalResist;
    [global::ProtoBuf.ProtoMember(65, IsRequired = true, Name=@"abnormalResist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell abnormalResist
    {
      get { return _abnormalResist; }
      set { _abnormalResist = value; }
    }
    private ProtoTable.UnionCell _criticalPercent;
    [global::ProtoBuf.ProtoMember(66, IsRequired = true, Name=@"criticalPercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell criticalPercent
    {
      get { return _criticalPercent; }
      set { _criticalPercent = value; }
    }
    private ProtoTable.UnionCell _cdReduceRate;
    [global::ProtoBuf.ProtoMember(67, IsRequired = true, Name=@"cdReduceRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell cdReduceRate
    {
      get { return _cdReduceRate; }
      set { _cdReduceRate = value; }
    }
    private ProtoTable.UnionCell _attackAddRate;
    [global::ProtoBuf.ProtoMember(68, IsRequired = true, Name=@"attackAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell attackAddRate
    {
      get { return _attackAddRate; }
      set { _attackAddRate = value; }
    }
    private ProtoTable.UnionCell _magicAttackAddRate;
    [global::ProtoBuf.ProtoMember(69, IsRequired = true, Name=@"magicAttackAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell magicAttackAddRate
    {
      get { return _magicAttackAddRate; }
      set { _magicAttackAddRate = value; }
    }
    private ProtoTable.UnionCell _defenceAddRate;
    [global::ProtoBuf.ProtoMember(70, IsRequired = true, Name=@"defenceAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell defenceAddRate
    {
      get { return _defenceAddRate; }
      set { _defenceAddRate = value; }
    }
    private ProtoTable.UnionCell _magicDefenceAddRate;
    [global::ProtoBuf.ProtoMember(71, IsRequired = true, Name=@"magicDefenceAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell magicDefenceAddRate
    {
      get { return _magicDefenceAddRate; }
      set { _magicDefenceAddRate = value; }
    }
    private ProtoTable.UnionCell _ignoreDefAttackAddRate;
    [global::ProtoBuf.ProtoMember(72, IsRequired = true, Name=@"ignoreDefAttackAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ignoreDefAttackAddRate
    {
      get { return _ignoreDefAttackAddRate; }
      set { _ignoreDefAttackAddRate = value; }
    }
    private ProtoTable.UnionCell _ignoreDefMagicAttackAddRate;
    [global::ProtoBuf.ProtoMember(73, IsRequired = true, Name=@"ignoreDefMagicAttackAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ignoreDefMagicAttackAddRate
    {
      get { return _ignoreDefMagicAttackAddRate; }
      set { _ignoreDefMagicAttackAddRate = value; }
    }
    private ProtoTable.UnionCell _attachAddDamageFix;
    [global::ProtoBuf.ProtoMember(74, IsRequired = true, Name=@"attachAddDamageFix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell attachAddDamageFix
    {
      get { return _attachAddDamageFix; }
      set { _attachAddDamageFix = value; }
    }
    private ProtoTable.UnionCell _attachAddDamagePercent;
    [global::ProtoBuf.ProtoMember(75, IsRequired = true, Name=@"attachAddDamagePercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell attachAddDamagePercent
    {
      get { return _attachAddDamagePercent; }
      set { _attachAddDamagePercent = value; }
    }
    private ProtoTable.UnionCell _addDamageFix;
    [global::ProtoBuf.ProtoMember(76, IsRequired = true, Name=@"addDamageFix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell addDamageFix
    {
      get { return _addDamageFix; }
      set { _addDamageFix = value; }
    }
    private ProtoTable.UnionCell _addDamagePercent;
    [global::ProtoBuf.ProtoMember(77, IsRequired = true, Name=@"addDamagePercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell addDamagePercent
    {
      get { return _addDamagePercent; }
      set { _addDamagePercent = value; }
    }
    private ProtoTable.UnionCell _reduceDamageFix;
    [global::ProtoBuf.ProtoMember(78, IsRequired = true, Name=@"reduceDamageFix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell reduceDamageFix
    {
      get { return _reduceDamageFix; }
      set { _reduceDamageFix = value; }
    }
    private int _reduceDamageFixType;
    [global::ProtoBuf.ProtoMember(79, IsRequired = true, Name=@"reduceDamageFixType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int reduceDamageFixType
    {
      get { return _reduceDamageFixType; }
      set { _reduceDamageFixType = value; }
    }
    private ProtoTable.UnionCell _reduceDamagePercent;
    [global::ProtoBuf.ProtoMember(80, IsRequired = true, Name=@"reduceDamagePercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell reduceDamagePercent
    {
      get { return _reduceDamagePercent; }
      set { _reduceDamagePercent = value; }
    }
    private int _reduceDamagePercentType;
    [global::ProtoBuf.ProtoMember(81, IsRequired = true, Name=@"reduceDamagePercentType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int reduceDamagePercentType
    {
      get { return _reduceDamagePercentType; }
      set { _reduceDamagePercentType = value; }
    }
    private ProtoTable.UnionCell _reflectDamageFix;
    [global::ProtoBuf.ProtoMember(82, IsRequired = true, Name=@"reflectDamageFix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell reflectDamageFix
    {
      get { return _reflectDamageFix; }
      set { _reflectDamageFix = value; }
    }
    private int _reflectDamageFixType;
    [global::ProtoBuf.ProtoMember(83, IsRequired = true, Name=@"reflectDamageFixType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int reflectDamageFixType
    {
      get { return _reflectDamageFixType; }
      set { _reflectDamageFixType = value; }
    }
    private ProtoTable.UnionCell _reflectDamagePercent;
    [global::ProtoBuf.ProtoMember(84, IsRequired = true, Name=@"reflectDamagePercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell reflectDamagePercent
    {
      get { return _reflectDamagePercent; }
      set { _reflectDamagePercent = value; }
    }
    private int _reflectDamagePercentType;
    [global::ProtoBuf.ProtoMember(85, IsRequired = true, Name=@"reflectDamagePercentType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int reflectDamagePercentType
    {
      get { return _reflectDamagePercentType; }
      set { _reflectDamagePercentType = value; }
    }
    private ProtoTable.UnionCell _level;
    [global::ProtoBuf.ProtoMember(86, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell level
    {
      get { return _level; }
      set { _level = value; }
    }
    private ProtoTable.UnionCell _skill_mpCostReduceRate;
    [global::ProtoBuf.ProtoMember(87, IsRequired = true, Name=@"skill_mpCostReduceRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_mpCostReduceRate
    {
      get { return _skill_mpCostReduceRate; }
      set { _skill_mpCostReduceRate = value; }
    }
    private ProtoTable.UnionCell _skill_cdReduceRate;
    [global::ProtoBuf.ProtoMember(88, IsRequired = true, Name=@"skill_cdReduceRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_cdReduceRate
    {
      get { return _skill_cdReduceRate; }
      set { _skill_cdReduceRate = value; }
    }
    private ProtoTable.UnionCell _skill_speedAddFactor;
    [global::ProtoBuf.ProtoMember(89, IsRequired = true, Name=@"skill_speedAddFactor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_speedAddFactor
    {
      get { return _skill_speedAddFactor; }
      set { _skill_speedAddFactor = value; }
    }
    private ProtoTable.UnionCell _skill_hitRateAdd;
    [global::ProtoBuf.ProtoMember(90, IsRequired = true, Name=@"skill_hitRateAdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_hitRateAdd
    {
      get { return _skill_hitRateAdd; }
      set { _skill_hitRateAdd = value; }
    }
    private ProtoTable.UnionCell _skill_criticalHitRateAdd;
    [global::ProtoBuf.ProtoMember(91, IsRequired = true, Name=@"skill_criticalHitRateAdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_criticalHitRateAdd
    {
      get { return _skill_criticalHitRateAdd; }
      set { _skill_criticalHitRateAdd = value; }
    }
    private ProtoTable.UnionCell _skill_attackAddRate;
    [global::ProtoBuf.ProtoMember(92, IsRequired = true, Name=@"skill_attackAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_attackAddRate
    {
      get { return _skill_attackAddRate; }
      set { _skill_attackAddRate = value; }
    }
    private ProtoTable.UnionCell _skill_hardAddRate;
    [global::ProtoBuf.ProtoMember(93, IsRequired = true, Name=@"skill_hardAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell skill_hardAddRate
    {
      get { return _skill_hardAddRate; }
      set { _skill_hardAddRate = value; }
    }
    private ProtoTable.UnionCell _ai_warlike;
    [global::ProtoBuf.ProtoMember(94, IsRequired = true, Name=@"ai_warlike", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ai_warlike
    {
      get { return _ai_warlike; }
      set { _ai_warlike = value; }
    }
    private ProtoTable.UnionCell _ai_sight;
    [global::ProtoBuf.ProtoMember(95, IsRequired = true, Name=@"ai_sight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ai_sight
    {
      get { return _ai_sight; }
      set { _ai_sight = value; }
    }
    private ProtoTable.UnionCell _ai_attackProb;
    [global::ProtoBuf.ProtoMember(96, IsRequired = true, Name=@"ai_attackProb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell ai_attackProb
    {
      get { return _ai_attackProb; }
      set { _ai_attackProb = value; }
    }
    private int _summon_monsterID;
    [global::ProtoBuf.ProtoMember(97, IsRequired = true, Name=@"summon_monsterID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_monsterID
    {
      get { return _summon_monsterID; }
      set { _summon_monsterID = value; }
    }
    private int _summon_monsterLevel;
    [global::ProtoBuf.ProtoMember(98, IsRequired = true, Name=@"summon_monsterLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_monsterLevel
    {
      get { return _summon_monsterLevel; }
      set { _summon_monsterLevel = value; }
    }
    private int _summon_existTime;
    [global::ProtoBuf.ProtoMember(99, IsRequired = true, Name=@"summon_existTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_existTime
    {
      get { return _summon_existTime; }
      set { _summon_existTime = value; }
    }
    private int _summon_posType;
    [global::ProtoBuf.ProtoMember(100, IsRequired = true, Name=@"summon_posType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_posType
    {
      get { return _summon_posType; }
      set { _summon_posType = value; }
    }
    private int _summon_display;
    [global::ProtoBuf.ProtoMember(101, IsRequired = true, Name=@"summon_display", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_display
    {
      get { return _summon_display; }
      set { _summon_display = value; }
    }
    private int _summon_num;
    [global::ProtoBuf.ProtoMember(102, IsRequired = true, Name=@"summon_num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_num
    {
      get { return _summon_num; }
      set { _summon_num = value; }
    }
    private int _summon_relation;
    [global::ProtoBuf.ProtoMember(103, IsRequired = true, Name=@"summon_relation", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_relation
    {
      get { return _summon_relation; }
      set { _summon_relation = value; }
    }
    private int _summon_numLimit;
    [global::ProtoBuf.ProtoMember(104, IsRequired = true, Name=@"summon_numLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int summon_numLimit
    {
      get { return _summon_numLimit; }
      set { _summon_numLimit = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _summon_entity = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(105, Name=@"summon_entity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> summon_entity
    {
      get { return _summon_entity; }
    }
  
    private int _duplicate_percent;
    [global::ProtoBuf.ProtoMember(106, IsRequired = true, Name=@"duplicate_percent", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int duplicate_percent
    {
      get { return _duplicate_percent; }
      set { _duplicate_percent = value; }
    }
    private int _duplicate_max;
    [global::ProtoBuf.ProtoMember(107, IsRequired = true, Name=@"duplicate_max", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int duplicate_max
    {
      get { return _duplicate_max; }
      set { _duplicate_max = value; }
    }
    private ProtoTable.UnionCell _expAddRate;
    [global::ProtoBuf.ProtoMember(108, IsRequired = true, Name=@"expAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell expAddRate
    {
      get { return _expAddRate; }
      set { _expAddRate = value; }
    }
    private ProtoTable.UnionCell _goldAddRate;
    [global::ProtoBuf.ProtoMember(109, IsRequired = true, Name=@"goldAddRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell goldAddRate
    {
      get { return _goldAddRate; }
      set { _goldAddRate = value; }
    }
    private int _taskDropAddRate;
    [global::ProtoBuf.ProtoMember(110, IsRequired = true, Name=@"taskDropAddRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int taskDropAddRate
    {
      get { return _taskDropAddRate; }
      set { _taskDropAddRate = value; }
    }
    private int _PinkDropAddRate;
    [global::ProtoBuf.ProtoMember(111, IsRequired = true, Name=@"PinkDropAddRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PinkDropAddRate
    {
      get { return _PinkDropAddRate; }
      set { _PinkDropAddRate = value; }
    }
    private int _durationType;
    [global::ProtoBuf.ProtoMember(112, IsRequired = true, Name=@"durationType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int durationType
    {
      get { return _durationType; }
      set { _durationType = value; }
    }
    private int _duration;
    [global::ProtoBuf.ProtoMember(113, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private string _DescriptionA;
    [global::ProtoBuf.ProtoMember(114, IsRequired = true, Name=@"DescriptionA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionA
    {
      get { return _DescriptionA; }
      set { _DescriptionA = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueA = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(115, Name=@"ValueA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueA
    {
      get { return _ValueA; }
    }
  
    private string _DescriptionB;
    [global::ProtoBuf.ProtoMember(116, IsRequired = true, Name=@"DescriptionB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionB
    {
      get { return _DescriptionB; }
      set { _DescriptionB = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueB = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(117, Name=@"ValueB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueB
    {
      get { return _ValueB; }
    }
  
    private string _DescriptionC;
    [global::ProtoBuf.ProtoMember(118, IsRequired = true, Name=@"DescriptionC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionC
    {
      get { return _DescriptionC; }
      set { _DescriptionC = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueC = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(119, Name=@"ValueC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueC
    {
      get { return _ValueC; }
    }
  
    private string _DescriptionD;
    [global::ProtoBuf.ProtoMember(120, IsRequired = true, Name=@"DescriptionD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionD
    {
      get { return _DescriptionD; }
      set { _DescriptionD = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueD = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(121, Name=@"ValueD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueD
    {
      get { return _ValueD; }
    }
  
    private string _DescriptionE;
    [global::ProtoBuf.ProtoMember(122, IsRequired = true, Name=@"DescriptionE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionE
    {
      get { return _DescriptionE; }
      set { _DescriptionE = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueE = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(123, Name=@"ValueE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueE
    {
      get { return _ValueE; }
    }
  
    private string _DescriptionF;
    [global::ProtoBuf.ProtoMember(124, IsRequired = true, Name=@"DescriptionF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionF
    {
      get { return _DescriptionF; }
      set { _DescriptionF = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueF = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(125, Name=@"ValueF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueF
    {
      get { return _ValueF; }
    }
  
    private string _DescriptionG;
    [global::ProtoBuf.ProtoMember(126, IsRequired = true, Name=@"DescriptionG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionG
    {
      get { return _DescriptionG; }
      set { _DescriptionG = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueG = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(127, Name=@"ValueG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueG
    {
      get { return _ValueG; }
    }
  
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Name LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Name = source.ReadString();
                    break;
                    
            case 3:   //Description LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Description = source.ReadString();
                    break;
                    
            case 4:   //Icon LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Icon = source.ReadString();
                    break;
                    
            case 5:   //Type LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Type = source.ReadInt32();
                    break;
                    
            case 6:   //WorkType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    WorkType = source.ReadInt32();
                    break;
                    
            case 7:   //DispelType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    DispelType = source.ReadInt32();
                    break;
                    
            case 8:   //IsQuickPressSupport LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    IsQuickPressSupport = source.ReadInt32();
                    break;
                    
            case 9:   //EffectShaderName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EffectShaderName = source.ReadString();
                    break;
                    
            case 10:   //HeadName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    HeadName = source.ReadString();
                    break;
                    
            case 11:   //IsShowSpell LABEL_REQUIRED TYPE_BOOL  TwosComplement
                    IsShowSpell = source.ReadBoolean();
                    break;
                    
            case 12:   //BirthEffect LABEL_REQUIRED TYPE_STRING  TwosComplement
                    BirthEffect = source.ReadString();
                    break;
                    
            case 13:   //BirthEffectLocate LABEL_REQUIRED TYPE_STRING  TwosComplement
                    BirthEffectLocate = source.ReadString();
                    break;
                    
            case 14:   //EffectName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EffectName = source.ReadString();
                    break;
                    
            case 15:   //EffectLocateName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EffectLocateName = source.ReadString();
                    break;
                    
            case 16:   //EffectLoop LABEL_REQUIRED TYPE_BOOL  TwosComplement
                    EffectLoop = source.ReadBoolean();
                    break;
                    
            case 17:   //EndEffect LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EndEffect = source.ReadString();
                    break;
                    
            case 18:   //EndEffectLocate LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EndEffectLocate = source.ReadString();
                    break;
                    
            case 19:   //EffectConfigPath LABEL_REQUIRED TYPE_STRING  TwosComplement
                    EffectConfigPath = source.ReadString();
                    break;
                    
            case 20:   //HurtEffectName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    HurtEffectName = source.ReadString();
                    break;
                    
            case 21:   //HurtEffectLocateName LABEL_REQUIRED TYPE_STRING  TwosComplement
                    HurtEffectLocateName = source.ReadString();
                    break;
                    
            case 22:   //BuffAIPath LABEL_REQUIRED TYPE_STRING  TwosComplement
                    BuffAIPath = source.ReadString();
                    break;
                    
            case 23:   //TargetState LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    TargetState = source.ReadInt32();
                    break;
                    
            case 24:   //Overlay LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Overlay = source.ReadInt32();
                    break;
                    
            case 25:   //OverlayLimit LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    OverlayLimit = source.ReadInt32();
                    break;
                    
            case 26:   //TriggerInterval LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    TriggerInterval = source.ReadInt32();
                    break;
                    
            case 27:   //StateChange LABEL_REPEATED TYPE_SINT32  ZigZag
                    int StateChangefield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        StateChange.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(StateChangefield));
                    break;
                    
            case 28:   //AbilityChange LABEL_REPEATED TYPE_SINT32  ZigZag
                    int AbilityChangefield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        AbilityChange.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(AbilityChangefield));
                    break;
                    
            case 29:   //UseSkillIDs LABEL_REPEATED TYPE_SINT32  ZigZag
                    int UseSkillIDsfield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        UseSkillIDs.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(UseSkillIDsfield));
                    break;
                    
            case 30:   //DispelBuffType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    DispelBuffType = source.ReadInt32();
                    break;
                    
            case 31:   //TriggerBuffInfoIDs LABEL_REPEATED TYPE_SINT32  ZigZag
                    int TriggerBuffInfoIDsfield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        TriggerBuffInfoIDs.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(TriggerBuffInfoIDsfield));
                    break;
                    
            case 32:   //MechanismID LABEL_REPEATED TYPE_SINT32  ZigZag
                    int MechanismIDfield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        MechanismID.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(MechanismIDfield));
                    break;
                    
            case 33:   //hp LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    hp = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken hptoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    hp.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(hptoken, source);
                    break;
                    
            case 34:   //mp LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    mp = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken mptoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    mp.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(mptoken, source);
                    break;
                    
            case 35:   //hpRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    hpRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken hpRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    hpRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(hpRatetoken, source);
                    break;
                    
            case 36:   //mpRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    mpRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken mpRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    mpRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(mpRatetoken, source);
                    break;
                    
            case 37:   //currentHpRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    currentHpRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken currentHpRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    currentHpRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(currentHpRatetoken, source);
                    break;
                    
            case 38:   //baseAtk LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    baseAtk = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken baseAtktoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    baseAtk.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(baseAtktoken, source);
                    break;
                    
            case 39:   //baseInt LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    baseInt = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken baseInttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    baseInt.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(baseInttoken, source);
                    break;
                    
            case 40:   //sta LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    sta = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken statoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    sta.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(statoken, source);
                    break;
                    
            case 41:   //spr LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    spr = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken sprtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    spr.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(sprtoken, source);
                    break;
                    
            case 42:   //atkAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    atkAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken atkAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    atkAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(atkAddRatetoken, source);
                    break;
                    
            case 43:   //intAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    intAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken intAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    intAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(intAddRatetoken, source);
                    break;
                    
            case 44:   //staAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    staAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken staAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    staAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(staAddRatetoken, source);
                    break;
                    
            case 45:   //sprAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    sprAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken sprAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    sprAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(sprAddRatetoken, source);
                    break;
                    
            case 46:   //maxHp LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    maxHp = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken maxHptoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    maxHp.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(maxHptoken, source);
                    break;
                    
            case 47:   //maxMp LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    maxMp = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken maxMptoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    maxMp.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(maxMptoken, source);
                    break;
                    
            case 48:   //maxHpAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    maxHpAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken maxHpAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    maxHpAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(maxHpAddRatetoken, source);
                    break;
                    
            case 49:   //maxMpAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    maxMpAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken maxMpAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    maxMpAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(maxMpAddRatetoken, source);
                    break;
                    
            case 50:   //hpRecover LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    hpRecover = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken hpRecovertoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    hpRecover.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(hpRecovertoken, source);
                    break;
                    
            case 51:   //mpRecover LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    mpRecover = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken mpRecovertoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    mpRecover.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(mpRecovertoken, source);
                    break;
                    
            case 52:   //attack LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    attack = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken attacktoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    attack.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(attacktoken, source);
                    break;
                    
            case 53:   //magicAttack LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    magicAttack = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken magicAttacktoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    magicAttack.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(magicAttacktoken, source);
                    break;
                    
            case 54:   //defence LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    defence = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken defencetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    defence.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(defencetoken, source);
                    break;
                    
            case 55:   //magicDefence LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    magicDefence = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken magicDefencetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    magicDefence.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(magicDefencetoken, source);
                    break;
                    
            case 56:   //attackSpeed LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    attackSpeed = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken attackSpeedtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    attackSpeed.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(attackSpeedtoken, source);
                    break;
                    
            case 57:   //spellSpeed LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    spellSpeed = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken spellSpeedtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    spellSpeed.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(spellSpeedtoken, source);
                    break;
                    
            case 58:   //moveSpeed LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    moveSpeed = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken moveSpeedtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    moveSpeed.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(moveSpeedtoken, source);
                    break;
                    
            case 59:   //ciriticalAttack LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ciriticalAttack = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ciriticalAttacktoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ciriticalAttack.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ciriticalAttacktoken, source);
                    break;
                    
            case 60:   //ciriticalMagicAttack LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ciriticalMagicAttack = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ciriticalMagicAttacktoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ciriticalMagicAttack.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ciriticalMagicAttacktoken, source);
                    break;
                    
            case 61:   //dex LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    dex = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken dextoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    dex.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(dextoken, source);
                    break;
                    
            case 62:   //dodge LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    dodge = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken dodgetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    dodge.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(dodgetoken, source);
                    break;
                    
            case 63:   //frozen LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    frozen = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken frozentoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    frozen.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(frozentoken, source);
                    break;
                    
            case 64:   //hard LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    hard = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken hardtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    hard.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(hardtoken, source);
                    break;
                    
            case 65:   //abnormalResist LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    abnormalResist = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken abnormalResisttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    abnormalResist.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(abnormalResisttoken, source);
                    break;
                    
            case 66:   //criticalPercent LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    criticalPercent = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken criticalPercenttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    criticalPercent.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(criticalPercenttoken, source);
                    break;
                    
            case 67:   //cdReduceRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    cdReduceRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken cdReduceRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    cdReduceRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(cdReduceRatetoken, source);
                    break;
                    
            case 68:   //attackAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    attackAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken attackAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    attackAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(attackAddRatetoken, source);
                    break;
                    
            case 69:   //magicAttackAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    magicAttackAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken magicAttackAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    magicAttackAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(magicAttackAddRatetoken, source);
                    break;
                    
            case 70:   //defenceAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    defenceAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken defenceAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    defenceAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(defenceAddRatetoken, source);
                    break;
                    
            case 71:   //magicDefenceAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    magicDefenceAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken magicDefenceAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    magicDefenceAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(magicDefenceAddRatetoken, source);
                    break;
                    
            case 72:   //ignoreDefAttackAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ignoreDefAttackAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ignoreDefAttackAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ignoreDefAttackAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ignoreDefAttackAddRatetoken, source);
                    break;
                    
            case 73:   //ignoreDefMagicAttackAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ignoreDefMagicAttackAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ignoreDefMagicAttackAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ignoreDefMagicAttackAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ignoreDefMagicAttackAddRatetoken, source);
                    break;
                    
            case 74:   //attachAddDamageFix LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    attachAddDamageFix = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken attachAddDamageFixtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    attachAddDamageFix.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(attachAddDamageFixtoken, source);
                    break;
                    
            case 75:   //attachAddDamagePercent LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    attachAddDamagePercent = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken attachAddDamagePercenttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    attachAddDamagePercent.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(attachAddDamagePercenttoken, source);
                    break;
                    
            case 76:   //addDamageFix LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    addDamageFix = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken addDamageFixtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    addDamageFix.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(addDamageFixtoken, source);
                    break;
                    
            case 77:   //addDamagePercent LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    addDamagePercent = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken addDamagePercenttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    addDamagePercent.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(addDamagePercenttoken, source);
                    break;
                    
            case 78:   //reduceDamageFix LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    reduceDamageFix = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken reduceDamageFixtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    reduceDamageFix.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(reduceDamageFixtoken, source);
                    break;
                    
            case 79:   //reduceDamageFixType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    reduceDamageFixType = source.ReadInt32();
                    break;
                    
            case 80:   //reduceDamagePercent LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    reduceDamagePercent = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken reduceDamagePercenttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    reduceDamagePercent.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(reduceDamagePercenttoken, source);
                    break;
                    
            case 81:   //reduceDamagePercentType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    reduceDamagePercentType = source.ReadInt32();
                    break;
                    
            case 82:   //reflectDamageFix LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    reflectDamageFix = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken reflectDamageFixtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    reflectDamageFix.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(reflectDamageFixtoken, source);
                    break;
                    
            case 83:   //reflectDamageFixType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    reflectDamageFixType = source.ReadInt32();
                    break;
                    
            case 84:   //reflectDamagePercent LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    reflectDamagePercent = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken reflectDamagePercenttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    reflectDamagePercent.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(reflectDamagePercenttoken, source);
                    break;
                    
            case 85:   //reflectDamagePercentType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    reflectDamagePercentType = source.ReadInt32();
                    break;
                    
            case 86:   //level LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    level = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken leveltoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    level.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(leveltoken, source);
                    break;
                    
            case 87:   //skill_mpCostReduceRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_mpCostReduceRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_mpCostReduceRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_mpCostReduceRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_mpCostReduceRatetoken, source);
                    break;
                    
            case 88:   //skill_cdReduceRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_cdReduceRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_cdReduceRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_cdReduceRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_cdReduceRatetoken, source);
                    break;
                    
            case 89:   //skill_speedAddFactor LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_speedAddFactor = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_speedAddFactortoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_speedAddFactor.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_speedAddFactortoken, source);
                    break;
                    
            case 90:   //skill_hitRateAdd LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_hitRateAdd = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_hitRateAddtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_hitRateAdd.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_hitRateAddtoken, source);
                    break;
                    
            case 91:   //skill_criticalHitRateAdd LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_criticalHitRateAdd = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_criticalHitRateAddtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_criticalHitRateAdd.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_criticalHitRateAddtoken, source);
                    break;
                    
            case 92:   //skill_attackAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_attackAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_attackAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_attackAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_attackAddRatetoken, source);
                    break;
                    
            case 93:   //skill_hardAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    skill_hardAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken skill_hardAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    skill_hardAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(skill_hardAddRatetoken, source);
                    break;
                    
            case 94:   //ai_warlike LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ai_warlike = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ai_warliketoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ai_warlike.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ai_warliketoken, source);
                    break;
                    
            case 95:   //ai_sight LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ai_sight = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ai_sighttoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ai_sight.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ai_sighttoken, source);
                    break;
                    
            case 96:   //ai_attackProb LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    ai_attackProb = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken ai_attackProbtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    ai_attackProb.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(ai_attackProbtoken, source);
                    break;
                    
            case 97:   //summon_monsterID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_monsterID = source.ReadInt32();
                    break;
                    
            case 98:   //summon_monsterLevel LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_monsterLevel = source.ReadInt32();
                    break;
                    
            case 99:   //summon_existTime LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_existTime = source.ReadInt32();
                    break;
                    
            case 100:   //summon_posType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_posType = source.ReadInt32();
                    break;
                    
            case 101:   //summon_display LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_display = source.ReadInt32();
                    break;
                    
            case 102:   //summon_num LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_num = source.ReadInt32();
                    break;
                    
            case 103:   //summon_relation LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_relation = source.ReadInt32();
                    break;
                    
            case 104:   //summon_numLimit LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    summon_numLimit = source.ReadInt32();
                    break;
                    
            case 105:   //summon_entity LABEL_REPEATED TYPE_SINT32  ZigZag
                    int summon_entityfield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        summon_entity.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(summon_entityfield));
                    break;
                    
            case 106:   //duplicate_percent LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    duplicate_percent = source.ReadInt32();
                    break;
                    
            case 107:   //duplicate_max LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    duplicate_max = source.ReadInt32();
                    break;
                    
            case 108:   //expAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    expAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken expAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    expAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(expAddRatetoken, source);
                    break;
                    
            case 109:   //goldAddRate LABEL_REQUIRED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    goldAddRate = new ProtoTable.UnionCell();
                    ProtoBuf.SubItemToken goldAddRatetoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                    goldAddRate.Parse(source);
                    ProtoBuf.ProtoReader.EndSubItem(goldAddRatetoken, source);
                    break;
                    
            case 110:   //taskDropAddRate LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    taskDropAddRate = source.ReadInt32();
                    break;
                    
            case 111:   //PinkDropAddRate LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    PinkDropAddRate = source.ReadInt32();
                    break;
                    
            case 112:   //durationType LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    durationType = source.ReadInt32();
                    break;
                    
            case 113:   //duration LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    duration = source.ReadInt32();
                    break;
                    
            case 114:   //DescriptionA LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionA = source.ReadString();
                    break;
                    
            case 115:   //ValueA LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueAfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueAtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueAtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueAtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueAtoken, source);
                        ValueA.Add(ValueAtemp);
                    } while (source.TryReadFieldHeader(ValueAfield));
                    break;
                    
            case 116:   //DescriptionB LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionB = source.ReadString();
                    break;
                    
            case 117:   //ValueB LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueBfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueBtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueBtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueBtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueBtoken, source);
                        ValueB.Add(ValueBtemp);
                    } while (source.TryReadFieldHeader(ValueBfield));
                    break;
                    
            case 118:   //DescriptionC LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionC = source.ReadString();
                    break;
                    
            case 119:   //ValueC LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueCfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueCtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueCtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueCtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueCtoken, source);
                        ValueC.Add(ValueCtemp);
                    } while (source.TryReadFieldHeader(ValueCfield));
                    break;
                    
            case 120:   //DescriptionD LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionD = source.ReadString();
                    break;
                    
            case 121:   //ValueD LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueDfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueDtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueDtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueDtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueDtoken, source);
                        ValueD.Add(ValueDtemp);
                    } while (source.TryReadFieldHeader(ValueDfield));
                    break;
                    
            case 122:   //DescriptionE LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionE = source.ReadString();
                    break;
                    
            case 123:   //ValueE LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueEfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueEtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueEtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueEtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueEtoken, source);
                        ValueE.Add(ValueEtemp);
                    } while (source.TryReadFieldHeader(ValueEfield));
                    break;
                    
            case 124:   //DescriptionF LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionF = source.ReadString();
                    break;
                    
            case 125:   //ValueF LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueFfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueFtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueFtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueFtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueFtoken, source);
                        ValueF.Add(ValueFtemp);
                    } while (source.TryReadFieldHeader(ValueFfield));
                    break;
                    
            case 126:   //DescriptionG LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DescriptionG = source.ReadString();
                    break;
                    
            case 127:   //ValueG LABEL_REPEATED TYPE_MESSAGE .ProtoTable.UnionCell TwosComplement
                    int ValueGfield = source.FieldNumber;
                    do
                    {
                        ProtoTable.UnionCell ValueGtemp = new ProtoTable.UnionCell();
                        ProtoBuf.SubItemToken ValueGtoken = ProtoBuf.ProtoReader.StartSubItem(source); 
                        ValueGtemp.Parse(source);
                        ProtoBuf.ProtoReader.EndSubItem(ValueGtoken, source);
                        ValueG.Add(ValueGtemp);
                    } while (source.TryReadFieldHeader(ValueGfield));
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}