//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DeathTowerAwardTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeathTowerAwardTable")]
  public partial class DeathTowerAwardTable : global::ProtoBuf.IExtensible
  {
    public DeathTowerAwardTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Floor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Floor", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Floor
    {
      get { return _Floor; }
      set { _Floor = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _WirrorSoul;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"WirrorSoul", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WirrorSoul
    {
      get { return _WirrorSoul; }
      set { _WirrorSoul = value; }
    }
    private int _Drop;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Drop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Drop
    {
      get { return _Drop; }
      set { _Drop = value; }
    }
    private int _AwardItem;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"AwardItem", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AwardItem
    {
      get { return _AwardItem; }
      set { _AwardItem = value; }
    }
    private int _AwardItemNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"AwardItemNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AwardItemNum
    {
      get { return _AwardItemNum; }
      set { _AwardItemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}