//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DropItemTable2.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DropItemTable2")]
  public partial class DropItemTable2 : global::ProtoBuf.IExtensible
  {
    public DropItemTable2() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _GroupID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GroupID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int GroupID
    {
      get { return _GroupID; }
      set { _GroupID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ChooseNumSet = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ChooseNumSet", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ChooseNumSet
    {
      get { return _ChooseNumSet; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _NumProbSet = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"NumProbSet", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> NumProbSet
    {
      get { return _NumProbSet; }
    }
  
    private int _DataType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DataType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DataType
    {
      get { return _DataType; }
      set { _DataType = value; }
    }
    private int _ItemID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private int _ItemProb;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ItemProb", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemProb
    {
      get { return _ItemProb; }
      set { _ItemProb = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ItemNum = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"ItemNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ItemNum
    {
      get { return _ItemNum; }
    }
  
    private int _IsRareControl;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"IsRareControl", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsRareControl
    {
      get { return _IsRareControl; }
      set { _IsRareControl = value; }
    }
    private int _TaskID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"TaskID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TaskID
    {
      get { return _TaskID; }
      set { _TaskID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _OccuAddition = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"OccuAddition", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> OccuAddition
    {
      get { return _OccuAddition; }
    }
  
    private int _AdditionProb;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"AdditionProb", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AdditionProb
    {
      get { return _AdditionProb; }
      set { _AdditionProb = value; }
    }
    private int _DropItemType;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"DropItemType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DropItemType
    {
      get { return _DropItemType; }
      set { _DropItemType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}