//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DungeonTable.proto
// Note: requires additional types generated from: Union.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonTable")]
  public partial class DungeonTable : global::ProtoBuf.IExtensible
  {
    public DungeonTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Oldname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Oldname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Oldname
    {
      get { return _Oldname; }
      set { _Oldname = value; }
    }
    private string _TumbPath;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TumbPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TumbPath
    {
      get { return _TumbPath; }
      set { _TumbPath = value; }
    }
    private string _TumbChPath;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TumbChPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TumbChPath
    {
      get { return _TumbChPath; }
      set { _TumbChPath = value; }
    }
    private string _LoadingBgPath;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"LoadingBgPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoadingBgPath
    {
      get { return _LoadingBgPath; }
      set { _LoadingBgPath = value; }
    }
    private string _Description;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _HardDescription;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"HardDescription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HardDescription
    {
      get { return _HardDescription; }
      set { _HardDescription = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private ProtoTable.DungeonTable.eType _Type;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.DungeonTable.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private ProtoTable.DungeonTable.eSubType _SubType;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"SubType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.DungeonTable.eSubType SubType
    {
      get { return _SubType; }
      set { _SubType = value; }
    }
    private ProtoTable.DungeonTable.eHard _Hard;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.DungeonTable.eHard Hard
    {
      get { return _Hard; }
      set { _Hard = value; }
    }
    private string _RecommendLevel;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"RecommendLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RecommendLevel
    {
      get { return _RecommendLevel; }
      set { _RecommendLevel = value; }
    }
    private int _HardAdaptType;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"HardAdaptType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HardAdaptType
    {
      get { return _HardAdaptType; }
      set { _HardAdaptType = value; }
    }
    private int _MaxHardAdaptLevel;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"MaxHardAdaptLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxHardAdaptLevel
    {
      get { return _MaxHardAdaptLevel; }
      set { _MaxHardAdaptLevel = value; }
    }
    private int _SingleBarValue;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"SingleBarValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SingleBarValue
    {
      get { return _SingleBarValue; }
      set { _SingleBarValue = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _DropItems = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"DropItems", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> DropItems
    {
      get { return _DropItems; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HellDropItems = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"HellDropItems", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HellDropItems
    {
      get { return _HellDropItems; }
    }
  
    private int _MinLevel;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"MinLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MinLevel
    {
      get { return _MinLevel; }
      set { _MinLevel = value; }
    }
    private int _storyTaskID;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"storyTaskID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int storyTaskID
    {
      get { return _storyTaskID; }
      set { _storyTaskID = value; }
    }
    private int _PreTaskID;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PreTaskID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PreTaskID
    {
      get { return _PreTaskID; }
      set { _PreTaskID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _storyDungeonIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"storyDungeonIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> storyDungeonIDs
    {
      get { return _storyDungeonIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PreDungeonIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"PreDungeonIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PreDungeonIDs
    {
      get { return _PreDungeonIDs; }
    }
  
    private string _DungeonLoadingConfig;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"DungeonLoadingConfig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DungeonLoadingConfig
    {
      get { return _DungeonLoadingConfig; }
      set { _DungeonLoadingConfig = value; }
    }
    private string _DungeonConfig;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"DungeonConfig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DungeonConfig
    {
      get { return _DungeonConfig; }
      set { _DungeonConfig = value; }
    }
    private int _IsExpAdapt;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"IsExpAdapt", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsExpAdapt
    {
      get { return _IsExpAdapt; }
      set { _IsExpAdapt = value; }
    }
    private int _ExpReward;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"ExpReward", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExpReward
    {
      get { return _ExpReward; }
      set { _ExpReward = value; }
    }
    private ProtoTable.UnionCell _TimeSplitArg;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"TimeSplitArg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell TimeSplitArg
    {
      get { return _TimeSplitArg; }
      set { _TimeSplitArg = value; }
    }
    private ProtoTable.UnionCell _RebornSplitArg;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"RebornSplitArg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell RebornSplitArg
    {
      get { return _RebornSplitArg; }
      set { _RebornSplitArg = value; }
    }
    private ProtoTable.UnionCell _HitSplitArg;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"HitSplitArg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HitSplitArg
    {
      get { return _HitSplitArg; }
      set { _HitSplitArg = value; }
    }
    private int _TimeArg;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"TimeArg", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TimeArg
    {
      get { return _TimeArg; }
      set { _TimeArg = value; }
    }
    private int _BackHitArg;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"BackHitArg", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BackHitArg
    {
      get { return _BackHitArg; }
      set { _BackHitArg = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _NormalMonsterDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(33, Name=@"NormalMonsterDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> NormalMonsterDrop
    {
      get { return _NormalMonsterDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _EliteMonsterDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(34, Name=@"EliteMonsterDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> EliteMonsterDrop
    {
      get { return _EliteMonsterDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BossMonsterDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(35, Name=@"BossMonsterDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BossMonsterDrop
    {
      get { return _BossMonsterDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _DungeonDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(36, Name=@"DungeonDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> DungeonDrop
    {
      get { return _DungeonDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _DungeonFirstDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(37, Name=@"DungeonFirstDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> DungeonFirstDrop
    {
      get { return _DungeonFirstDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _DestructionDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(38, Name=@"DestructionDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> DestructionDrop
    {
      get { return _DestructionDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _EasterEggDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(39, Name=@"EasterEggDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> EasterEggDrop
    {
      get { return _EasterEggDrop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _TaskDrop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(40, Name=@"TaskDrop", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> TaskDrop
    {
      get { return _TaskDrop; }
    }
  
    private int _CostFatiguePerArea;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"CostFatiguePerArea", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CostFatiguePerArea
    {
      get { return _CostFatiguePerArea; }
      set { _CostFatiguePerArea = value; }
    }
    private int _TicketID;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"TicketID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TicketID
    {
      get { return _TicketID; }
      set { _TicketID = value; }
    }
    private int _TicketNum;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"TicketNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TicketNum
    {
      get { return _TicketNum; }
      set { _TicketNum = value; }
    }
    private int _HellTicketNum;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"HellTicketNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellTicketNum
    {
      get { return _HellTicketNum; }
      set { _HellTicketNum = value; }
    }
    private int _HellTask;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"HellTask", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellTask
    {
      get { return _HellTask; }
      set { _HellTask = value; }
    }
    private int _HellDrop1;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"HellDrop1", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellDrop1
    {
      get { return _HellDrop1; }
      set { _HellDrop1 = value; }
    }
    private int _HellDrop2;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"HellDrop2", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellDrop2
    {
      get { return _HellDrop2; }
      set { _HellDrop2 = value; }
    }
    private int _RebornCount;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"RebornCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RebornCount
    {
      get { return _RebornCount; }
      set { _RebornCount = value; }
    }
    private string _BGMPath;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"BGMPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BGMPath
    {
      get { return _BGMPath; }
      set { _BGMPath = value; }
    }
    private string _HellHardBGMPath;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"HellHardBGMPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HellHardBGMPath
    {
      get { return _HellHardBGMPath; }
      set { _HellHardBGMPath = value; }
    }
    private string _HellDamnHardBGMPath;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"HellDamnHardBGMPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HellDamnHardBGMPath
    {
      get { return _HellDamnHardBGMPath; }
      set { _HellDamnHardBGMPath = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _RaceEndDropBaseMulti = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(52, Name=@"RaceEndDropBaseMulti", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> RaceEndDropBaseMulti
    {
      get { return _RaceEndDropBaseMulti; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _RaceEndDropMultiCost = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(53, Name=@"RaceEndDropMultiCost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> RaceEndDropMultiCost
    {
      get { return _RaceEndDropMultiCost; }
    }
  
    private int _ActivityID;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"ActivityID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ActivityID
    {
      get { return _ActivityID; }
      set { _ActivityID = value; }
    }
    private int _DailyMaxTime;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"DailyMaxTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DailyMaxTime
    {
      get { return _DailyMaxTime; }
      set { _DailyMaxTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _BuffDrugConfig = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(56, Name=@"BuffDrugConfig", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BuffDrugConfig
    {
      get { return _BuffDrugConfig; }
    }
  
    private int _MostCostStamina;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"MostCostStamina", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MostCostStamina
    {
      get { return _MostCostStamina; }
      set { _MostCostStamina = value; }
    }
    private int _HellSplitLevel;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"HellSplitLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellSplitLevel
    {
      get { return _HellSplitLevel; }
      set { _HellSplitLevel = value; }
    }
    private int _HellSplitLevelWeight;
    [global::ProtoBuf.ProtoMember(59, IsRequired = true, Name=@"HellSplitLevelWeight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HellSplitLevelWeight
    {
      get { return _HellSplitLevelWeight; }
      set { _HellSplitLevelWeight = value; }
    }
    private int _OpenAutoFight;
    [global::ProtoBuf.ProtoMember(60, IsRequired = true, Name=@"OpenAutoFight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int OpenAutoFight
    {
      get { return _OpenAutoFight; }
      set { _OpenAutoFight = value; }
    }
    private int _OnlyRaceEndProfit;
    [global::ProtoBuf.ProtoMember(61, IsRequired = true, Name=@"OnlyRaceEndProfit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int OnlyRaceEndProfit
    {
      get { return _OnlyRaceEndProfit; }
      set { _OnlyRaceEndProfit = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"L_NORMAL", Value=0)]
      L_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"L_STORY", Value=1)]
      L_STORY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"L_ACTIVITY", Value=2)]
      L_ACTIVITY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"L_DEADTOWER", Value=3)]
      L_DEADTOWER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSubType")]
    public enum eSubType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_NORMAL", Value=0)]
      S_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_YUANGU", Value=1)]
      S_YUANGU = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_NIUTOUGUAI", Value=2)]
      S_NIUTOUGUAI = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_NANBUXIGU", Value=3)]
      S_NANBUXIGU = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_SIWANGZHITA", Value=4)]
      S_SIWANGZHITA = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_NEWBIEGUIDE", Value=5)]
      S_NEWBIEGUIDE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_PK", Value=6)]
      S_PK = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_JINBI", Value=7)]
      S_JINBI = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_HELL", Value=8)]
      S_HELL = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_GUILDPK", Value=9)]
      S_GUILDPK = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_HELL_ENTRY", Value=10)]
      S_HELL_ENTRY = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_TEAM_BOSS", Value=11)]
      S_TEAM_BOSS = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eHard")]
    public enum eHard
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=0)]
      NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RISK", Value=1)]
      RISK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARRIOR", Value=2)]
      WARRIOR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KING", Value=3)]
      KING = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}