//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EffectTable.proto
// Note: requires additional types generated from: Union.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectTable")]
  public partial class EffectTable : global::ProtoBuf.IExtensible
  {
    public EffectTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _SkillID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }
    private ProtoTable.EffectTable.eEffectTargetType _EffectTargetType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"EffectTargetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eEffectTargetType EffectTargetType
    {
      get { return _EffectTargetType; }
      set { _EffectTargetType = value; }
    }
    private int _HasDamage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"HasDamage", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HasDamage
    {
      get { return _HasDamage; }
      set { _HasDamage = value; }
    }
    private ProtoTable.EffectTable.eAvoidDamageType _AvoidDamageType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"AvoidDamageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eAvoidDamageType AvoidDamageType
    {
      get { return _AvoidDamageType; }
      set { _AvoidDamageType = value; }
    }
    private ProtoTable.EffectTable.eDamageType _DamageType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"DamageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eDamageType DamageType
    {
      get { return _DamageType; }
      set { _DamageType = value; }
    }
    private ProtoTable.EffectTable.eDamageDistanceType _DamageDistanceType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"DamageDistanceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eDamageDistanceType DamageDistanceType
    {
      get { return _DamageDistanceType; }
      set { _DamageDistanceType = value; }
    }
    private int _DamageMaxCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"DamageMaxCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DamageMaxCount
    {
      get { return _DamageMaxCount; }
      set { _DamageMaxCount = value; }
    }
    private ProtoTable.UnionCell _AttachCritical;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"AttachCritical", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell AttachCritical
    {
      get { return _AttachCritical; }
      set { _AttachCritical = value; }
    }
    private ProtoTable.UnionCell _HitThroughRate;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"HitThroughRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HitThroughRate
    {
      get { return _HitThroughRate; }
      set { _HitThroughRate = value; }
    }
    private ProtoTable.UnionCell _DamageRateAPC;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"DamageRateAPC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell DamageRateAPC
    {
      get { return _DamageRateAPC; }
      set { _DamageRateAPC = value; }
    }
    private ProtoTable.UnionCell _DamageRate;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"DamageRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell DamageRate
    {
      get { return _DamageRate; }
      set { _DamageRate = value; }
    }
    private ProtoTable.UnionCell _DamageFixedValue;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"DamageFixedValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell DamageFixedValue
    {
      get { return _DamageFixedValue; }
      set { _DamageFixedValue = value; }
    }
    private ProtoTable.UnionCell _DamageRatePVP;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"DamageRatePVP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell DamageRatePVP
    {
      get { return _DamageRatePVP; }
      set { _DamageRatePVP = value; }
    }
    private ProtoTable.UnionCell _DamageFixedValuePVP;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"DamageFixedValuePVP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell DamageFixedValuePVP
    {
      get { return _DamageFixedValuePVP; }
      set { _DamageFixedValuePVP = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _AttachMonsterRace = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"AttachMonsterRace", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AttachMonsterRace
    {
      get { return _AttachMonsterRace; }
    }
  
    private ProtoTable.UnionCell _AttachDamageRate;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"AttachDamageRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell AttachDamageRate
    {
      get { return _AttachDamageRate; }
      set { _AttachDamageRate = value; }
    }
    private bool _IsCanMiss;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"IsCanMiss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsCanMiss
    {
      get { return _IsCanMiss; }
      set { _IsCanMiss = value; }
    }
    private bool _HitGrab;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"HitGrab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool HitGrab
    {
      get { return _HitGrab; }
      set { _HitGrab = value; }
    }
    private ProtoTable.UnionCell _HardValue;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"HardValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HardValue
    {
      get { return _HardValue; }
      set { _HardValue = value; }
    }
    private bool _UseStandardWeight;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"UseStandardWeight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool UseStandardWeight
    {
      get { return _UseStandardWeight; }
      set { _UseStandardWeight = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ClearTargetState = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"ClearTargetState", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ClearTargetState
    {
      get { return _ClearTargetState; }
    }
  
    private bool _UseNoBlock;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"UseNoBlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool UseNoBlock
    {
      get { return _UseNoBlock; }
      set { _UseNoBlock = value; }
    }
    private ProtoTable.UnionCell _Attack;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"Attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell Attack
    {
      get { return _Attack; }
      set { _Attack = value; }
    }
    private ProtoTable.UnionCell _FloatingRate;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"FloatingRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell FloatingRate
    {
      get { return _FloatingRate; }
      set { _FloatingRate = value; }
    }
    private ProtoTable.UnionCell _HitFloatXForce;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"HitFloatXForce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HitFloatXForce
    {
      get { return _HitFloatXForce; }
      set { _HitFloatXForce = value; }
    }
    private ProtoTable.UnionCell _HitFloatYForce;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"HitFloatYForce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HitFloatYForce
    {
      get { return _HitFloatYForce; }
      set { _HitFloatYForce = value; }
    }
    private int _RepeatAttackInterval;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"RepeatAttackInterval", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RepeatAttackInterval
    {
      get { return _RepeatAttackInterval; }
      set { _RepeatAttackInterval = value; }
    }
    private ProtoTable.EffectTable.eHitEffect _HitEffect;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"HitEffect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eHitEffect HitEffect
    {
      get { return _HitEffect; }
      set { _HitEffect = value; }
    }
    private bool _HitPause;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"HitPause", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool HitPause
    {
      get { return _HitPause; }
      set { _HitPause = value; }
    }
    private int _HitPauseTime;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"HitPauseTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitPauseTime
    {
      get { return _HitPauseTime; }
      set { _HitPauseTime = value; }
    }
    private int _HitScreenShakeTime;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"HitScreenShakeTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitScreenShakeTime
    {
      get { return _HitScreenShakeTime; }
      set { _HitScreenShakeTime = value; }
    }
    private int _HitScreenShakeSpeed;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"HitScreenShakeSpeed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitScreenShakeSpeed
    {
      get { return _HitScreenShakeSpeed; }
      set { _HitScreenShakeSpeed = value; }
    }
    private int _HitScreenShakeX;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"HitScreenShakeX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitScreenShakeX
    {
      get { return _HitScreenShakeX; }
      set { _HitScreenShakeX = value; }
    }
    private int _HitScreenShakeY;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"HitScreenShakeY", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitScreenShakeY
    {
      get { return _HitScreenShakeY; }
      set { _HitScreenShakeY = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _AttachEntity = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(37, Name=@"AttachEntity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AttachEntity
    {
      get { return _AttachEntity; }
    }
  
    private int _SummonID;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"SummonID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonID
    {
      get { return _SummonID; }
      set { _SummonID = value; }
    }
    private ProtoTable.EffectTable.eSummonPosType _SummonPosType;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"SummonPosType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eSummonPosType SummonPosType
    {
      get { return _SummonPosType; }
      set { _SummonPosType = value; }
    }
    private int _SummonDisplay;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"SummonDisplay", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonDisplay
    {
      get { return _SummonDisplay; }
      set { _SummonDisplay = value; }
    }
    private ProtoTable.UnionCell _SummonNum;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"SummonNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell SummonNum
    {
      get { return _SummonNum; }
      set { _SummonNum = value; }
    }
    private ProtoTable.UnionCell _SummonLevel;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"SummonLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell SummonLevel
    {
      get { return _SummonLevel; }
      set { _SummonLevel = value; }
    }
    private int _SummonNumLimit;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"SummonNumLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonNumLimit
    {
      get { return _SummonNumLimit; }
      set { _SummonNumLimit = value; }
    }
    private ProtoTable.UnionCell _SummonGroupNumLimit;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"SummonGroupNumLimit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell SummonGroupNumLimit
    {
      get { return _SummonGroupNumLimit; }
      set { _SummonGroupNumLimit = value; }
    }
    private int _SummonGroup;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"SummonGroup", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonGroup
    {
      get { return _SummonGroup; }
      set { _SummonGroup = value; }
    }
    private int _SummonRelation;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"SummonRelation", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonRelation
    {
      get { return _SummonRelation; }
      set { _SummonRelation = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _SummonRandList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(47, Name=@"SummonRandList", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> SummonRandList
    {
      get { return _SummonRandList; }
    }
  
    private int _BuffID;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"BuffID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BuffID
    {
      get { return _BuffID; }
      set { _BuffID = value; }
    }
    private ProtoTable.UnionCell _BuffLevel;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"BuffLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell BuffLevel
    {
      get { return _BuffLevel; }
      set { _BuffLevel = value; }
    }
    private ProtoTable.EffectTable.eBuffTarget _BuffTarget;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"BuffTarget", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EffectTable.eBuffTarget BuffTarget
    {
      get { return _BuffTarget; }
      set { _BuffTarget = value; }
    }
    private ProtoTable.UnionCell _AttachBuffRate;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"AttachBuffRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell AttachBuffRate
    {
      get { return _AttachBuffRate; }
      set { _AttachBuffRate = value; }
    }
    private ProtoTable.UnionCell _AttachBuffTime;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"AttachBuffTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell AttachBuffTime
    {
      get { return _AttachBuffTime; }
      set { _AttachBuffTime = value; }
    }
    private ProtoTable.UnionCell _BuffAttack;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"BuffAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell BuffAttack
    {
      get { return _BuffAttack; }
      set { _BuffAttack = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _BuffInfoID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(54, Name=@"BuffInfoID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BuffInfoID
    {
      get { return _BuffInfoID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PVPBuffInfoID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(55, Name=@"PVPBuffInfoID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PVPBuffInfoID
    {
      get { return _PVPBuffInfoID; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eEffectTargetType")]
    public enum eEffectTargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"H_NONE", Value=0)]
      H_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H_ENEMY", Value=1)]
      H_ENEMY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H_FRIEND", Value=2)]
      H_FRIEND = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eAvoidDamageType")]
    public enum eAvoidDamageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AV_NONE", Value=0)]
      AV_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AV_AREA", Value=1)]
      AV_AREA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AV_FACINGAWAY", Value=2)]
      AV_FACINGAWAY = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDamageType")]
    public enum eDamageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYSIC", Value=1)]
      PHYSIC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGIC", Value=2)]
      MAGIC = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDamageDistanceType")]
    public enum eDamageDistanceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEAR", Value=1)]
      NEAR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAR", Value=2)]
      FAR = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eHitEffect")]
    public enum eHitEffect
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIT", Value=0)]
      HIT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HITFLY", Value=1)]
      HITFLY = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSummonPosType")]
    public enum eSummonPosType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACE", Value=0)]
      FACE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORIGIN", Value=1)]
      ORIGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACE_FORCE", Value=2)]
      FACE_FORCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACE_BLACK", Value=3)]
      FACE_BLACK = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBuffTarget")]
    public enum eBuffTarget
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF", Value=0)]
      SELF = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENEMY", Value=1)]
      ENEMY = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}