//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipStrModTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipStrModTable")]
  public partial class EquipStrModTable : global::ProtoBuf.IExtensible
  {
    public EquipStrModTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _WpStrenthMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"WpStrenthMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> WpStrenthMod
    {
      get { return _WpStrenthMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _WpColorQaMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"WpColorQaMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> WpColorQaMod
    {
      get { return _WpColorQaMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _WpColorQbMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"WpColorQbMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> WpColorQbMod
    {
      get { return _WpColorQbMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ArmStrenthMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ArmStrenthMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ArmStrenthMod
    {
      get { return _ArmStrenthMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ArmColorQaMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"ArmColorQaMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ArmColorQaMod
    {
      get { return _ArmColorQaMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ArmColorQbMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ArmColorQbMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ArmColorQbMod
    {
      get { return _ArmColorQbMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _JewStrenthMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"JewStrenthMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> JewStrenthMod
    {
      get { return _JewStrenthMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _JewColorQaMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"JewColorQaMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> JewColorQaMod
    {
      get { return _JewColorQaMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _JewColorQbMod = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"JewColorQbMod", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> JewColorQbMod
    {
      get { return _JewColorQbMod; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HugeSword = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"HugeSword", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HugeSword
    {
      get { return _HugeSword; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Katana = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"Katana", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Katana
    {
      get { return _Katana; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ShortSword = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"ShortSword", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ShortSword
    {
      get { return _ShortSword; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BeamSword = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"BeamSword", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BeamSword
    {
      get { return _BeamSword; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Blunt = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"Blunt", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Blunt
    {
      get { return _Blunt; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Revolver = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"Revolver", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Revolver
    {
      get { return _Revolver; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _CrossBow = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"CrossBow", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> CrossBow
    {
      get { return _CrossBow; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HandCannon = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"HandCannon", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HandCannon
    {
      get { return _HandCannon; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoRifle = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"AutoRifle", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AutoRifle
    {
      get { return _AutoRifle; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoPistal = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"AutoPistal", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AutoPistal
    {
      get { return _AutoPistal; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MagicStick = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"MagicStick", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MagicStick
    {
      get { return _MagicStick; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Twig = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"Twig", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Twig
    {
      get { return _Twig; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Pike = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"Pike", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Pike
    {
      get { return _Pike; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Stick = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(24, Name=@"Stick", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Stick
    {
      get { return _Stick; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Besom = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"Besom", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Besom
    {
      get { return _Besom; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}