//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipAttrTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipAttrTable")]
  public partial class EquipAttrTable : global::ProtoBuf.IExtensible
  {
    public EquipAttrTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Atk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private int _MagicAtk;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MagicAtk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MagicAtk
    {
      get { return _MagicAtk; }
      set { _MagicAtk = value; }
    }
    private int _Def;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private int _MagicDef;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"MagicDef", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MagicDef
    {
      get { return _MagicDef; }
      set { _MagicDef = value; }
    }
    private int _Strenth;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Strenth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Strenth
    {
      get { return _Strenth; }
      set { _Strenth = value; }
    }
    private int _Intellect;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Intellect", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Intellect
    {
      get { return _Intellect; }
      set { _Intellect = value; }
    }
    private int _Spirit;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Spirit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Spirit
    {
      get { return _Spirit; }
      set { _Spirit = value; }
    }
    private int _Stamina;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Stamina", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Stamina
    {
      get { return _Stamina; }
      set { _Stamina = value; }
    }
    private int _PhySkillMp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"PhySkillMp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PhySkillMp
    {
      get { return _PhySkillMp; }
      set { _PhySkillMp = value; }
    }
    private int _PhySkillCd;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"PhySkillCd", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PhySkillCd
    {
      get { return _PhySkillCd; }
      set { _PhySkillCd = value; }
    }
    private int _MagSkillMp;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"MagSkillMp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MagSkillMp
    {
      get { return _MagSkillMp; }
      set { _MagSkillMp = value; }
    }
    private int _MagSkillCd;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"MagSkillCd", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MagSkillCd
    {
      get { return _MagSkillCd; }
      set { _MagSkillCd = value; }
    }
    private int _HPMax;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"HPMax", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HPMax
    {
      get { return _HPMax; }
      set { _HPMax = value; }
    }
    private int _MPMax;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"MPMax", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MPMax
    {
      get { return _MPMax; }
      set { _MPMax = value; }
    }
    private int _HPRecover;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"HPRecover", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HPRecover
    {
      get { return _HPRecover; }
      set { _HPRecover = value; }
    }
    private int _MPRecover;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"MPRecover", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MPRecover
    {
      get { return _MPRecover; }
      set { _MPRecover = value; }
    }
    private int _AttackSpeedRate;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"AttackSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AttackSpeedRate
    {
      get { return _AttackSpeedRate; }
      set { _AttackSpeedRate = value; }
    }
    private int _FireSpeedRate;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"FireSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int FireSpeedRate
    {
      get { return _FireSpeedRate; }
      set { _FireSpeedRate = value; }
    }
    private int _MoveSpeedRate;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"MoveSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MoveSpeedRate
    {
      get { return _MoveSpeedRate; }
      set { _MoveSpeedRate = value; }
    }
    private int _TownMoveSpeedRate;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"TownMoveSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TownMoveSpeedRate
    {
      get { return _TownMoveSpeedRate; }
      set { _TownMoveSpeedRate = value; }
    }
    private int _HitRate;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"HitRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HitRate
    {
      get { return _HitRate; }
      set { _HitRate = value; }
    }
    private int _AvoidRate;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"AvoidRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AvoidRate
    {
      get { return _AvoidRate; }
      set { _AvoidRate = value; }
    }
    private int _PhysicCrit;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"PhysicCrit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PhysicCrit
    {
      get { return _PhysicCrit; }
      set { _PhysicCrit = value; }
    }
    private int _MagicCrit;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"MagicCrit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MagicCrit
    {
      get { return _MagicCrit; }
      set { _MagicCrit = value; }
    }
    private int _Spasticity;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"Spasticity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Spasticity
    {
      get { return _Spasticity; }
      set { _Spasticity = value; }
    }
    private int _Jump;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"Jump", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Jump
    {
      get { return _Jump; }
      set { _Jump = value; }
    }
    private int _AttachRateScore;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"AttachRateScore", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AttachRateScore
    {
      get { return _AttachRateScore; }
      set { _AttachRateScore = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _AttachBuffInfoIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(30, Name=@"AttachBuffInfoIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AttachBuffInfoIDs
    {
      get { return _AttachBuffInfoIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AttachMechanismIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(31, Name=@"AttachMechanismIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AttachMechanismIDs
    {
      get { return _AttachMechanismIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PVPAttachBuffInfoIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(32, Name=@"PVPAttachBuffInfoIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PVPAttachBuffInfoIDs
    {
      get { return _PVPAttachBuffInfoIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PVPAttachMechanismIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(33, Name=@"PVPAttachMechanismIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PVPAttachMechanismIDs
    {
      get { return _PVPAttachMechanismIDs; }
    }
  
    private string _AttachBuffDesc;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"AttachBuffDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttachBuffDesc
    {
      get { return _AttachBuffDesc; }
      set { _AttachBuffDesc = value; }
    }
    private string _AttachMechanismDesc;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"AttachMechanismDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttachMechanismDesc
    {
      get { return _AttachMechanismDesc; }
      set { _AttachMechanismDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}