//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipForgeTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipForgeTable")]
  public partial class EquipForgeTable : global::ProtoBuf.IExtensible
  {
    public EquipForgeTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Material = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Material
    {
      get { return _Material; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _Price = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Price
    {
      get { return _Price; }
    }
  
    private string _MainTypeName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MainTypeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MainTypeName
    {
      get { return _MainTypeName; }
      set { _MainTypeName = value; }
    }
    private string _SubTypeName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SubTypeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SubTypeName
    {
      get { return _SubTypeName; }
      set { _SubTypeName = value; }
    }
    private int _RecommendLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"RecommendLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RecommendLevel
    {
      get { return _RecommendLevel; }
      set { _RecommendLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _RecommendJobs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"RecommendJobs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> RecommendJobs
    {
      get { return _RecommendJobs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}