//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipQLValueTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipQLValueTable")]
  public partial class EquipQLValueTable : global::ProtoBuf.IExtensible
  {
    public EquipQLValueTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private ProtoTable.EquipQLValueTable.ePart _Part;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Part", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EquipQLValueTable.ePart Part
    {
      get { return _Part; }
      set { _Part = value; }
    }
    private int _AtkDef;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AtkDef", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AtkDef
    {
      get { return _AtkDef; }
      set { _AtkDef = value; }
    }
    private int _FourDimensional;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"FourDimensional", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int FourDimensional
    {
      get { return _FourDimensional; }
      set { _FourDimensional = value; }
    }
    private int _PerfectAtkDef;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PerfectAtkDef", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PerfectAtkDef
    {
      get { return _PerfectAtkDef; }
      set { _PerfectAtkDef = value; }
    }
    private int _PerfectFourDimensional;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PerfectFourDimensional", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PerfectFourDimensional
    {
      get { return _PerfectFourDimensional; }
      set { _PerfectFourDimensional = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ePart")]
    public enum ePart
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON", Value=1)]
      WEAPON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOTH", Value=2)]
      CLOTH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEATHER", Value=3)]
      LEATHER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAVY", Value=4)]
      HEAVY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLATE", Value=5)]
      PLATE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIGHT", Value=6)]
      LIGHT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JEWELRY", Value=7)]
      JEWELRY = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}