//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipMasterTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipMasterTable")]
  public partial class EquipMasterTable : global::ProtoBuf.IExtensible
  {
    public EquipMasterTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _JobID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"JobID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int JobID
    {
      get { return _JobID; }
      set { _JobID = value; }
    }
    private int _Quality;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Quality", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Quality
    {
      get { return _Quality; }
      set { _Quality = value; }
    }
    private int _Part;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Part", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Part
    {
      get { return _Part; }
      set { _Part = value; }
    }
    private int _MaterialType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"MaterialType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaterialType
    {
      get { return _MaterialType; }
      set { _MaterialType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Atk = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"Atk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Atk
    {
      get { return _Atk; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MagicAtk = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"MagicAtk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MagicAtk
    {
      get { return _MagicAtk; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Def = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"Def", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Def
    {
      get { return _Def; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MagicDef = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"MagicDef", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MagicDef
    {
      get { return _MagicDef; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Strenth = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"Strenth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Strenth
    {
      get { return _Strenth; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Intellect = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"Intellect", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Intellect
    {
      get { return _Intellect; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Spirit = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"Spirit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Spirit
    {
      get { return _Spirit; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Stamina = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"Stamina", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Stamina
    {
      get { return _Stamina; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HPMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"HPMax", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HPMax
    {
      get { return _HPMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MPMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"MPMax", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MPMax
    {
      get { return _MPMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HPRecover = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"HPRecover", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HPRecover
    {
      get { return _HPRecover; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MPRecover = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"MPRecover", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MPRecover
    {
      get { return _MPRecover; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AttackSpeedRate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"AttackSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AttackSpeedRate
    {
      get { return _AttackSpeedRate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _FireSpeedRate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"FireSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> FireSpeedRate
    {
      get { return _FireSpeedRate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MoveSpeedRate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"MoveSpeedRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MoveSpeedRate
    {
      get { return _MoveSpeedRate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _HitRate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"HitRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HitRate
    {
      get { return _HitRate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AvoidRate = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"AvoidRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> AvoidRate
    {
      get { return _AvoidRate; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PhysicCrit = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"PhysicCrit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PhysicCrit
    {
      get { return _PhysicCrit; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MagicCrit = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(24, Name=@"MagicCrit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MagicCrit
    {
      get { return _MagicCrit; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Spasticity = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"Spasticity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Spasticity
    {
      get { return _Spasticity; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _Descs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(26, Name=@"Descs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Descs
    {
      get { return _Descs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}