//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FishTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FishTable")]
  public partial class FishTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public FishTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private string _Prefab;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Prefab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Prefab
    {
      get { return _Prefab; }
      set { _Prefab = value; }
    }
    private string _TraceFrame;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TraceFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TraceFrame
    {
      get { return _TraceFrame; }
      set { _TraceFrame = value; }
    }
    private int _Interval;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Interval", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Interval
    {
      get { return _Interval; }
      set { _Interval = value; }
    }
    private int _Speed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Speed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Speed
    {
      get { return _Speed; }
      set { _Speed = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Desc LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Desc = source.ReadString();
                    break;
                    
            case 3:   //Prefab LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Prefab = source.ReadString();
                    break;
                    
            case 4:   //TraceFrame LABEL_REQUIRED TYPE_STRING  TwosComplement
                    TraceFrame = source.ReadString();
                    break;
                    
            case 5:   //Interval LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Interval = source.ReadInt32();
                    break;
                    
            case 6:   //Speed LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Speed = source.ReadInt32();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}