//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FollowPetTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FollowPetTable")]
  public partial class FollowPetTable : global::ProtoBuf.IExtensible
  {
    public FollowPetTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _MonsterID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MonsterID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MonsterID
    {
      get { return _MonsterID; }
      set { _MonsterID = value; }
    }
    private int _GroupId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"GroupId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int GroupId
    {
      get { return _GroupId; }
      set { _GroupId = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private ProtoTable.FollowPetTable.eQuality _Quality;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.FollowPetTable.eQuality Quality
    {
      get { return _Quality; }
      set { _Quality = value; }
    }
    private int _TakeLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"TakeLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TakeLevel
    {
      get { return _TakeLevel; }
      set { _TakeLevel = value; }
    }
    private int _MaxStarLevel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"MaxStarLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxStarLevel
    {
      get { return _MaxStarLevel; }
      set { _MaxStarLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Skills = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"Skills", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Skills
    {
      get { return _Skills; }
    }
  
    private int _ItemID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private string _StarUpCondition;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"StarUpCondition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string StarUpCondition
    {
      get { return _StarUpCondition; }
      set { _StarUpCondition = value; }
    }
    private string _ChangeSkillConsume;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"ChangeSkillConsume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ChangeSkillConsume
    {
      get { return _ChangeSkillConsume; }
      set { _ChangeSkillConsume = value; }
    }
    private int _NotUnlockSkillCount;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"NotUnlockSkillCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int NotUnlockSkillCount
    {
      get { return _NotUnlockSkillCount; }
      set { _NotUnlockSkillCount = value; }
    }
    private int _ChangeSkillUnlock;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"ChangeSkillUnlock", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ChangeSkillUnlock
    {
      get { return _ChangeSkillUnlock; }
      set { _ChangeSkillUnlock = value; }
    }
    private int _RelationID;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"RelationID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RelationID
    {
      get { return _RelationID; }
      set { _RelationID = value; }
    }
    private string _StarsUpUnlockSkills;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"StarsUpUnlockSkills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string StarsUpUnlockSkills
    {
      get { return _StarsUpUnlockSkills; }
      set { _StarsUpUnlockSkills = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eQuality")]
    public enum eQuality
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUE", Value=0)]
      BLUE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURPLE", Value=1)]
      PURPLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINK", Value=2)]
      PINK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORANGE", Value=3)]
      ORANGE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}