//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildRewardTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildRewardTable")]
  public partial class GuildRewardTable : global::ProtoBuf.IExtensible
  {
    public GuildRewardTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _TargetScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TargetScore", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TargetScore
    {
      get { return _TargetScore; }
      set { _TargetScore = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _ItemReward = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ItemReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ItemReward
    {
      get { return _ItemReward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}