//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildTable")]
  public partial class GuildTable : global::ProtoBuf.IExtensible
  {
    public GuildTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _MemberNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private int _ShopLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ShopLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ShopLevel
    {
      get { return _ShopLevel; }
      set { _ShopLevel = value; }
    }
    private int _TableLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TableLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TableLevel
    {
      get { return _TableLevel; }
      set { _TableLevel = value; }
    }
    private int _DungeonLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DungeonLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DungeonLevel
    {
      get { return _DungeonLevel; }
      set { _DungeonLevel = value; }
    }
    private int _StatueLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"StatueLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int StatueLevel
    {
      get { return _StatueLevel; }
      set { _StatueLevel = value; }
    }
    private int _BattleLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"BattleLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BattleLevel
    {
      get { return _BattleLevel; }
      set { _BattleLevel = value; }
    }
    private int _WelfareLevel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"WelfareLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WelfareLevel
    {
      get { return _WelfareLevel; }
      set { _WelfareLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}