//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: JarBonus.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JarBonus")]
  public partial class JarBonus : global::ProtoBuf.IExtensible
  {
    public JarBonus() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private ProtoTable.JarBonus.eType _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.JarBonus.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Filter = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Filter", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Filter
    {
      get { return _Filter; }
    }
  
    private string _JarImage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"JarImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string JarImage
    {
      get { return _JarImage; }
      set { _JarImage = value; }
    }
    private string _JarEffect;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"JarEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string JarEffect
    {
      get { return _JarEffect; }
      set { _JarEffect = value; }
    }
    private int _ExBonusNum_1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ExBonusNum_1", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExBonusNum_1
    {
      get { return _ExBonusNum_1; }
      set { _ExBonusNum_1 = value; }
    }
    private int _ExBonusJarID_1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ExBonusJarID_1", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExBonusJarID_1
    {
      get { return _ExBonusJarID_1; }
      set { _ExBonusJarID_1 = value; }
    }
    private int _ExBonusNum_2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"ExBonusNum_2", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExBonusNum_2
    {
      get { return _ExBonusNum_2; }
      set { _ExBonusNum_2 = value; }
    }
    private int _ExBonusJarID_2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"ExBonusJarID_2", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExBonusJarID_2
    {
      get { return _ExBonusJarID_2; }
      set { _ExBonusJarID_2 = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _GetItemsAndNum = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(11, Name=@"GetItemsAndNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> GetItemsAndNum
    {
      get { return _GetItemsAndNum; }
    }
  
    private int _BuyMoneyType;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"BuyMoneyType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BuyMoneyType
    {
      get { return _BuyMoneyType; }
      set { _BuyMoneyType = value; }
    }
    private int _MoneyValue;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"MoneyValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MoneyValue
    {
      get { return _MoneyValue; }
      set { _MoneyValue = value; }
    }
    private int _DayBuyLimite;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"DayBuyLimite", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DayBuyLimite
    {
      get { return _DayBuyLimite; }
      set { _DayBuyLimite = value; }
    }
    private string _BuyLimitKey;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"BuyLimitKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BuyLimitKey
    {
      get { return _BuyLimitKey; }
      set { _BuyLimitKey = value; }
    }
    private int _NeedExItem;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"NeedExItem", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int NeedExItem
    {
      get { return _NeedExItem; }
      set { _NeedExItem = value; }
    }
    private int _ExItemID;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"ExItemID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExItemID
    {
      get { return _ExItemID; }
      set { _ExItemID = value; }
    }
    private int _ExItemCostNum;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"ExItemCostNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ExItemCostNum
    {
      get { return _ExItemCostNum; }
      set { _ExItemCostNum = value; }
    }
    private int _ComboBuyNum;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"ComboBuyNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ComboBuyNum
    {
      get { return _ComboBuyNum; }
      set { _ComboBuyNum = value; }
    }
    private int _ComboBuyDiscount;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"ComboBuyDiscount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ComboBuyDiscount
    {
      get { return _ComboBuyDiscount; }
      set { _ComboBuyDiscount = value; }
    }
    private string _CounterKey;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"CounterKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CounterKey
    {
      get { return _CounterKey; }
      set { _CounterKey = value; }
    }
    private int _GetPointType;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"GetPointType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int GetPointType
    {
      get { return _GetPointType; }
      set { _GetPointType = value; }
    }
    private int _GetPointNum;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"GetPointNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int GetPointNum
    {
      get { return _GetPointNum; }
      set { _GetPointNum = value; }
    }
    private string _GetPointCrit;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"GetPointCrit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GetPointCrit
    {
      get { return _GetPointCrit; }
      set { _GetPointCrit = value; }
    }
    private int _MaxFreeCount;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"MaxFreeCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxFreeCount
    {
      get { return _MaxFreeCount; }
      set { _MaxFreeCount = value; }
    }
    private int _FreeCD;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"FreeCD", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int FreeCD
    {
      get { return _FreeCD; }
      set { _FreeCD = value; }
    }
    private int _NeedRecord;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"NeedRecord", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int NeedRecord
    {
      get { return _NeedRecord; }
      set { _NeedRecord = value; }
    }
    private int _ActJarDisMaxNum;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"ActJarDisMaxNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ActJarDisMaxNum
    {
      get { return _ActJarDisMaxNum; }
      set { _ActJarDisMaxNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoneJar", Value=0)]
      NoneJar = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MagicJar", Value=1)]
      MagicJar = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldJar", Value=2)]
      GoldJar = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BudoJar", Value=3)]
      BudoJar = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WingJar", Value=101)]
      WingJar = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionJar", Value=102)]
      FashionJar = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipJar", Value=103)]
      EquipJar = 103
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}