//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: JarItemShowPool.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JarItemShowPool")]
  public partial class JarItemShowPool : global::ProtoBuf.IExtensible
  {
    public JarItemShowPool() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _JarType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"JarType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int JarType
    {
      get { return _JarType; }
      set { _JarType = value; }
    }
    private int _ItemID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private int _ItemNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ItemNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemNum
    {
      get { return _ItemNum; }
      set { _ItemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}