//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LocalSettingTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LocalSettingTable")]
  public partial class LocalSettingTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public LocalSettingTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private ProtoTable.LocalSettingTable.eSetting _Setting;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Setting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.LocalSettingTable.eSetting Setting
    {
      get { return _Setting; }
      set { _Setting = value; }
    }
    private string _FilePath;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"FilePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FilePath
    {
      get { return _FilePath; }
      set { _FilePath = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eSetting")]
    public enum eSetting
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUSIC_SETTING", Value=1)]
      MUSIC_SETTING = 1
    }
  
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Desc LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Desc = source.ReadString();
                    break;
                    
            case 3:   //Setting LABEL_REQUIRED TYPE_ENUM .ProtoTable.LocalSettingTable.eSetting TwosComplement
                    Setting = (ProtoTable.LocalSettingTable.eSetting)source.ReadInt32();
                    break;
                    
            case 4:   //FilePath LABEL_REQUIRED TYPE_STRING  TwosComplement
                    FilePath = source.ReadString();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}