//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MissionTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissionTable")]
  public partial class MissionTable : global::ProtoBuf.IExtensible
  {
    public MissionTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _TaskName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TaskName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TaskName
    {
      get { return _TaskName; }
      set { _TaskName = value; }
    }
    private int _SortID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SortID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SortID
    {
      get { return _SortID; }
      set { _SortID = value; }
    }
    private ProtoTable.MissionTable.eTaskType _TaskType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TaskType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eTaskType TaskType
    {
      get { return _TaskType; }
      set { _TaskType = value; }
    }
    private ProtoTable.MissionTable.eSubType _SubType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SubType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eSubType SubType
    {
      get { return _SubType; }
      set { _SubType = value; }
    }
    private ProtoTable.MissionTable.eCycleType _CycleType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"CycleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eCycleType CycleType
    {
      get { return _CycleType; }
      set { _CycleType = value; }
    }
    private int _CycleWeight;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"CycleWeight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CycleWeight
    {
      get { return _CycleWeight; }
      set { _CycleWeight = value; }
    }
    private ProtoTable.MissionTable.eDailyPoolType _DailyPoolType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"DailyPoolType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eDailyPoolType DailyPoolType
    {
      get { return _DailyPoolType; }
      set { _DailyPoolType = value; }
    }
    private int _PoolID;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"PoolID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PoolID
    {
      get { return _PoolID; }
      set { _PoolID = value; }
    }
    private ProtoTable.MissionTable.eTaskLevelType _TaskLevelType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"TaskLevelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eTaskLevelType TaskLevelType
    {
      get { return _TaskLevelType; }
      set { _TaskLevelType = value; }
    }
    private string _TaskInformationText;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"TaskInformationText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TaskInformationText
    {
      get { return _TaskInformationText; }
      set { _TaskInformationText = value; }
    }
    private string _TaskInitText;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"TaskInitText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TaskInitText
    {
      get { return _TaskInitText; }
      set { _TaskInitText = value; }
    }
    private string _TaskAcceptedText;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"TaskAcceptedText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TaskAcceptedText
    {
      get { return _TaskAcceptedText; }
      set { _TaskAcceptedText = value; }
    }
    private string _TaskFinishText;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"TaskFinishText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TaskFinishText
    {
      get { return _TaskFinishText; }
      set { _TaskFinishText = value; }
    }
    private int _MapID;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"MapID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MapID
    {
      get { return _MapID; }
      set { _MapID = value; }
    }
    private int _SeekingTarget;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"SeekingTarget", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SeekingTarget
    {
      get { return _SeekingTarget; }
      set { _SeekingTarget = value; }
    }
    private int _BefTaskDlgID;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"BefTaskDlgID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BefTaskDlgID
    {
      get { return _BefTaskDlgID; }
      set { _BefTaskDlgID = value; }
    }
    private int _InTaskDlgID;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"InTaskDlgID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int InTaskDlgID
    {
      get { return _InTaskDlgID; }
      set { _InTaskDlgID = value; }
    }
    private int _AftTaskDlgID;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"AftTaskDlgID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AftTaskDlgID
    {
      get { return _AftTaskDlgID; }
      set { _AftTaskDlgID = value; }
    }
    private int _PreTaskID;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"PreTaskID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PreTaskID
    {
      get { return _PreTaskID; }
      set { _PreTaskID = value; }
    }
    private int _SeverTake;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"SeverTake", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SeverTake
    {
      get { return _SeverTake; }
      set { _SeverTake = value; }
    }
    private int _MaxPlayerLv;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"MaxPlayerLv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxPlayerLv
    {
      get { return _MaxPlayerLv; }
      set { _MaxPlayerLv = value; }
    }
    private int _MinPlayerLv;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"MinPlayerLv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MinPlayerLv
    {
      get { return _MinPlayerLv; }
      set { _MinPlayerLv = value; }
    }
    private int _JobID;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"JobID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int JobID
    {
      get { return _JobID; }
      set { _JobID = value; }
    }
    private ProtoTable.MissionTable.eTaskFinishType _TaskFinishType;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"TaskFinishType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eTaskFinishType TaskFinishType
    {
      get { return _TaskFinishType; }
      set { _TaskFinishType = value; }
    }
    private string _LinkInfo;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"LinkInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LinkInfo
    {
      get { return _LinkInfo; }
      set { _LinkInfo = value; }
    }
    private int _LinkParam;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"LinkParam", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LinkParam
    {
      get { return _LinkParam; }
      set { _LinkParam = value; }
    }
    private string _OccuAward;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"OccuAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OccuAward
    {
      get { return _OccuAward; }
      set { _OccuAward = value; }
    }
    private string _Award;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"Award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Award
    {
      get { return _Award; }
      set { _Award = value; }
    }
    private int _RewardAdapter;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"RewardAdapter", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RewardAdapter
    {
      get { return _RewardAdapter; }
      set { _RewardAdapter = value; }
    }
    private int _AfterID;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"AfterID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AfterID
    {
      get { return _AfterID; }
      set { _AfterID = value; }
    }
    private ProtoTable.MissionTable.eAcceptType _AcceptType;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"AcceptType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eAcceptType AcceptType
    {
      get { return _AcceptType; }
      set { _AcceptType = value; }
    }
    private ProtoTable.MissionTable.eFinishType _FinishType;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"FinishType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.MissionTable.eFinishType FinishType
    {
      get { return _FinishType; }
      set { _FinishType = value; }
    }
    private int _MissionTakeNpc;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"MissionTakeNpc", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MissionTakeNpc
    {
      get { return _MissionTakeNpc; }
      set { _MissionTakeNpc = value; }
    }
    private int _MissionFinishNpc;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"MissionFinishNpc", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MissionFinishNpc
    {
      get { return _MissionFinishNpc; }
      set { _MissionFinishNpc = value; }
    }
    private string _MissionNpcIcon;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"MissionNpcIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MissionNpcIcon
    {
      get { return _MissionNpcIcon; }
      set { _MissionNpcIcon = value; }
    }
    private int _VitalityValue;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"VitalityValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int VitalityValue
    {
      get { return _VitalityValue; }
      set { _VitalityValue = value; }
    }
    private string _MissionParam;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"MissionParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MissionParam
    {
      get { return _MissionParam; }
      set { _MissionParam = value; }
    }
    private int _MissionOnOff;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"MissionOnOff", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MissionOnOff
    {
      get { return _MissionOnOff; }
      set { _MissionOnOff = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _MonsterIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(40, Name=@"MonsterIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MonsterIDs
    {
      get { return _MonsterIDs; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eTaskType")]
    public enum eTaskType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_DIALY", Value=0)]
      TT_DIALY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_MAIN", Value=1)]
      TT_MAIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_BRANCH", Value=2)]
      TT_BRANCH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ACHIEVEMENT", Value=3)]
      TT_ACHIEVEMENT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_SYSTEM", Value=4)]
      TT_SYSTEM = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ACTIVITY", Value=5)]
      TT_ACTIVITY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_EXTENTION", Value=6)]
      TT_EXTENTION = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_CHANGEJOB", Value=7)]
      TT_CHANGEJOB = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_AWAKEN", Value=8)]
      TT_AWAKEN = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_CYCLE", Value=9)]
      TT_CYCLE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_RED_PACKET", Value=10)]
      TT_RED_PACKET = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_TITLE", Value=11)]
      TT_TITLE = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSubType")]
    public enum eSubType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Daily_Null", Value=0)]
      Daily_Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Daily_Task", Value=1)]
      Daily_Task = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Daily_Prove", Value=2)]
      Daily_Prove = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dungeon_Mission", Value=3)]
      Dungeon_Mission = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dungeon_Chest", Value=4)]
      Dungeon_Chest = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chapter_Change", Value=5)]
      Chapter_Change = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eCycleType")]
    public enum eCycleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CYCLE_INVALID", Value=0)]
      CYCLE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CYCLE_DUNGEON", Value=1)]
      CYCLE_DUNGEON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CYCLE_SET_ITEM", Value=2)]
      CYCLE_SET_ITEM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CYCLE_STORY", Value=3)]
      CYCLE_STORY = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDailyPoolType")]
    public enum eDailyPoolType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_INVALID", Value=0)]
      DAILY_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_SURE", Value=1)]
      DAILY_SURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_DUNGEON", Value=2)]
      DAILY_DUNGEON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_FUNCTION", Value=3)]
      DAILY_FUNCTION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_ACTIVITY", Value=4)]
      DAILY_ACTIVITY = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eTaskLevelType")]
    public enum eTaskLevelType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC_NONE", Value=0)]
      NPC_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC_PROTECT", Value=1)]
      NPC_PROTECT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC_FIND", Value=2)]
      NPC_FIND = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eTaskFinishType")]
    public enum eTaskFinishType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_KILL", Value=0)]
      TFT_KILL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_PASS", Value=1)]
      TFT_PASS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_COLLECT", Value=2)]
      TFT_COLLECT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_TALK", Value=3)]
      TFT_TALK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_KILL_BY_TYPE", Value=4)]
      TFT_KILL_BY_TYPE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_FINISHMISSION_TYPE", Value=5)]
      TFT_FINISHMISSION_TYPE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_ACCESS_SHOP", Value=6)]
      TFT_ACCESS_SHOP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_SUBMIT_ITEM", Value=7)]
      TFT_SUBMIT_ITEM = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TFT_LINKS", Value=8)]
      TFT_LINKS = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eAcceptType")]
    public enum eAcceptType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACT_AUTO", Value=0)]
      ACT_AUTO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACT_NPC", Value=1)]
      ACT_NPC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACT_UI", Value=2)]
      ACT_UI = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFinishType")]
    public enum eFinishType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISH_TYPE_AUTO", Value=0)]
      FINISH_TYPE_AUTO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISH_TYPE_NPC", Value=1)]
      FINISH_TYPE_NPC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FINISH_TYPE_UI", Value=2)]
      FINISH_TYPE_UI = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}