//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NameTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NameTable")]
  public partial class NameTable : global::ProtoBuf.IExtensible
  {
    public NameTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _NameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NameType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int NameType
    {
      get { return _NameType; }
      set { _NameType = value; }
    }
    private string _NameText;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"NameText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NameText
    {
      get { return _NameText; }
      set { _NameText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}