//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PkHPLevelAdjustTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PkHPLevelAdjustTable")]
  public partial class PkHPLevelAdjustTable : global::ProtoBuf.IExtensible
  {
    public PkHPLevelAdjustTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _factor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"factor", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int factor
    {
      get { return _factor; }
      set { _factor = value; }
    }
    private int _Attackfactor;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Attackfactor", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Attackfactor
    {
      get { return _Attackfactor; }
      set { _Attackfactor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}