//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RetinueConsumeTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetinueConsumeTable")]
  public partial class RetinueConsumeTable : global::ProtoBuf.IExtensible
  {
    public RetinueConsumeTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }
    private int _Consume;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Consume", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Consume
    {
      get { return _Consume; }
      set { _Consume = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}