//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RewardAdapterTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RewardAdapterTable")]
  public partial class RewardAdapterTable : global::ProtoBuf.IExtensible
  {
    public RewardAdapterTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Level1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level1
    {
      get { return _Level1; }
      set { _Level1 = value; }
    }
    private string _Level2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Level2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level2
    {
      get { return _Level2; }
      set { _Level2 = value; }
    }
    private string _Level3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Level3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level3
    {
      get { return _Level3; }
      set { _Level3 = value; }
    }
    private string _Level4;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Level4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level4
    {
      get { return _Level4; }
      set { _Level4 = value; }
    }
    private string _Level5;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Level5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level5
    {
      get { return _Level5; }
      set { _Level5 = value; }
    }
    private string _Level6;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Level6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level6
    {
      get { return _Level6; }
      set { _Level6 = value; }
    }
    private string _Level7;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Level7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level7
    {
      get { return _Level7; }
      set { _Level7 = value; }
    }
    private string _Level8;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Level8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level8
    {
      get { return _Level8; }
      set { _Level8 = value; }
    }
    private string _Level9;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"Level9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level9
    {
      get { return _Level9; }
      set { _Level9 = value; }
    }
    private string _Level10;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Level10", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level10
    {
      get { return _Level10; }
      set { _Level10 = value; }
    }
    private string _Level11;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"Level11", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level11
    {
      get { return _Level11; }
      set { _Level11 = value; }
    }
    private string _Level12;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"Level12", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level12
    {
      get { return _Level12; }
      set { _Level12 = value; }
    }
    private string _Level13;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"Level13", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level13
    {
      get { return _Level13; }
      set { _Level13 = value; }
    }
    private string _Level14;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"Level14", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level14
    {
      get { return _Level14; }
      set { _Level14 = value; }
    }
    private string _Level15;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"Level15", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level15
    {
      get { return _Level15; }
      set { _Level15 = value; }
    }
    private string _Level16;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"Level16", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level16
    {
      get { return _Level16; }
      set { _Level16 = value; }
    }
    private string _Level17;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Level17", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level17
    {
      get { return _Level17; }
      set { _Level17 = value; }
    }
    private string _Level18;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"Level18", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level18
    {
      get { return _Level18; }
      set { _Level18 = value; }
    }
    private string _Level19;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"Level19", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level19
    {
      get { return _Level19; }
      set { _Level19 = value; }
    }
    private string _Level20;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"Level20", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level20
    {
      get { return _Level20; }
      set { _Level20 = value; }
    }
    private string _Level21;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"Level21", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level21
    {
      get { return _Level21; }
      set { _Level21 = value; }
    }
    private string _Level22;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"Level22", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level22
    {
      get { return _Level22; }
      set { _Level22 = value; }
    }
    private string _Level23;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"Level23", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level23
    {
      get { return _Level23; }
      set { _Level23 = value; }
    }
    private string _Level24;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"Level24", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level24
    {
      get { return _Level24; }
      set { _Level24 = value; }
    }
    private string _Level25;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"Level25", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level25
    {
      get { return _Level25; }
      set { _Level25 = value; }
    }
    private string _Level26;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"Level26", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level26
    {
      get { return _Level26; }
      set { _Level26 = value; }
    }
    private string _Level27;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"Level27", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level27
    {
      get { return _Level27; }
      set { _Level27 = value; }
    }
    private string _Level28;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"Level28", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level28
    {
      get { return _Level28; }
      set { _Level28 = value; }
    }
    private string _Level29;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"Level29", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level29
    {
      get { return _Level29; }
      set { _Level29 = value; }
    }
    private string _Level30;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"Level30", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level30
    {
      get { return _Level30; }
      set { _Level30 = value; }
    }
    private string _Level31;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"Level31", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level31
    {
      get { return _Level31; }
      set { _Level31 = value; }
    }
    private string _Level32;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"Level32", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level32
    {
      get { return _Level32; }
      set { _Level32 = value; }
    }
    private string _Level33;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"Level33", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level33
    {
      get { return _Level33; }
      set { _Level33 = value; }
    }
    private string _Level34;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"Level34", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level34
    {
      get { return _Level34; }
      set { _Level34 = value; }
    }
    private string _Level35;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"Level35", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level35
    {
      get { return _Level35; }
      set { _Level35 = value; }
    }
    private string _Level36;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"Level36", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level36
    {
      get { return _Level36; }
      set { _Level36 = value; }
    }
    private string _Level37;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"Level37", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level37
    {
      get { return _Level37; }
      set { _Level37 = value; }
    }
    private string _Level38;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"Level38", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level38
    {
      get { return _Level38; }
      set { _Level38 = value; }
    }
    private string _Level39;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"Level39", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level39
    {
      get { return _Level39; }
      set { _Level39 = value; }
    }
    private string _Level40;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"Level40", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level40
    {
      get { return _Level40; }
      set { _Level40 = value; }
    }
    private string _Level41;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"Level41", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level41
    {
      get { return _Level41; }
      set { _Level41 = value; }
    }
    private string _Level42;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"Level42", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level42
    {
      get { return _Level42; }
      set { _Level42 = value; }
    }
    private string _Level43;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"Level43", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level43
    {
      get { return _Level43; }
      set { _Level43 = value; }
    }
    private string _Level44;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"Level44", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level44
    {
      get { return _Level44; }
      set { _Level44 = value; }
    }
    private string _Level45;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"Level45", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level45
    {
      get { return _Level45; }
      set { _Level45 = value; }
    }
    private string _Level46;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"Level46", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level46
    {
      get { return _Level46; }
      set { _Level46 = value; }
    }
    private string _Level47;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"Level47", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level47
    {
      get { return _Level47; }
      set { _Level47 = value; }
    }
    private string _Level48;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"Level48", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level48
    {
      get { return _Level48; }
      set { _Level48 = value; }
    }
    private string _Level49;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"Level49", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level49
    {
      get { return _Level49; }
      set { _Level49 = value; }
    }
    private string _Level50;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"Level50", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level50
    {
      get { return _Level50; }
      set { _Level50 = value; }
    }
    private string _Level51;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"Level51", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level51
    {
      get { return _Level51; }
      set { _Level51 = value; }
    }
    private string _Level52;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"Level52", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level52
    {
      get { return _Level52; }
      set { _Level52 = value; }
    }
    private string _Level53;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"Level53", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level53
    {
      get { return _Level53; }
      set { _Level53 = value; }
    }
    private string _Level54;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"Level54", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level54
    {
      get { return _Level54; }
      set { _Level54 = value; }
    }
    private string _Level55;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"Level55", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level55
    {
      get { return _Level55; }
      set { _Level55 = value; }
    }
    private string _Level56;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"Level56", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level56
    {
      get { return _Level56; }
      set { _Level56 = value; }
    }
    private string _Level57;
    [global::ProtoBuf.ProtoMember(59, IsRequired = true, Name=@"Level57", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level57
    {
      get { return _Level57; }
      set { _Level57 = value; }
    }
    private string _Level58;
    [global::ProtoBuf.ProtoMember(60, IsRequired = true, Name=@"Level58", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level58
    {
      get { return _Level58; }
      set { _Level58 = value; }
    }
    private string _Level59;
    [global::ProtoBuf.ProtoMember(61, IsRequired = true, Name=@"Level59", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level59
    {
      get { return _Level59; }
      set { _Level59 = value; }
    }
    private string _Level60;
    [global::ProtoBuf.ProtoMember(62, IsRequired = true, Name=@"Level60", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level60
    {
      get { return _Level60; }
      set { _Level60 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}