//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SceneRegionTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneRegionTable")]
  public partial class SceneRegionTable : global::ProtoBuf.IExtensible
  {
    public SceneRegionTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private ProtoTable.SceneRegionTable.eType _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.SceneRegionTable.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private ProtoTable.SceneRegionTable.eDoorType _DoorType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DoorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.SceneRegionTable.eDoorType DoorType
    {
      get { return _DoorType; }
      set { _DoorType = value; }
    }
    private int _ResID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ResID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ResID
    {
      get { return _ResID; }
      set { _ResID = value; }
    }
    private int _ReplaceResID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ReplaceResID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ReplaceResID
    {
      get { return _ReplaceResID; }
      set { _ReplaceResID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _EffectID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"EffectID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> EffectID
    {
      get { return _EffectID; }
    }
  
    private int _RepeatTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"RepeatTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RepeatTime
    {
      get { return _RepeatTime; }
      set { _RepeatTime = value; }
    }
    private int _RepeatCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"RepeatCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RepeatCount
    {
      get { return _RepeatCount; }
      set { _RepeatCount = value; }
    }
    private int _FirstTimeToRepeat;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"FirstTimeToRepeat", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int FirstTimeToRepeat
    {
      get { return _FirstTimeToRepeat; }
      set { _FirstTimeToRepeat = value; }
    }
    private string _ActivedEffect;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ActivedEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActivedEffect
    {
      get { return _ActivedEffect; }
      set { _ActivedEffect = value; }
    }
    private string _Desc;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUFF", Value=0)]
      BUFF = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOOR", Value=1)]
      DOOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWNDOOR", Value=2)]
      TOWNDOOR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAP", Value=3)]
      TRAP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOOP", Value=4)]
      LOOP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIDE", Value=5)]
      RIDE = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDoorType")]
    public enum eDoorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_NONE", Value=-1)]
      DT_NONE = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEFT", Value=0)]
      LEFT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOP", Value=1)]
      TOP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIGHT", Value=2)]
      RIGHT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUTTOM", Value=3)]
      BUTTOM = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}