//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SeasonLevelTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SeasonLevelTable")]
  public partial class SeasonLevelTable : global::ProtoBuf.IExtensible
  {
    public SeasonLevelTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _PreId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PreId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int PreId
    {
      get { return _PreId; }
      set { _PreId = value; }
    }
    private int _AfterId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AfterId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AfterId
    {
      get { return _AfterId; }
      set { _AfterId = value; }
    }
    private ProtoTable.SeasonLevelTable.eMainLevel _MainLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MainLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.SeasonLevelTable.eMainLevel MainLevel
    {
      get { return _MainLevel; }
      set { _MainLevel = value; }
    }
    private int _SmallLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SmallLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SmallLevel
    {
      get { return _SmallLevel; }
      set { _SmallLevel = value; }
    }
    private int _Star;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Star", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Star
    {
      get { return _Star; }
      set { _Star = value; }
    }
    private int _MaxExp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"MaxExp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxExp
    {
      get { return _MaxExp; }
      set { _MaxExp = value; }
    }
    private int _MaxStar;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"MaxStar", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxStar
    {
      get { return _MaxStar; }
      set { _MaxStar = value; }
    }
    private int _HideScore;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"HideScore", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int HideScore
    {
      get { return _HideScore; }
      set { _HideScore = value; }
    }
    private int _CanMatchRobot;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"CanMatchRobot", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CanMatchRobot
    {
      get { return _CanMatchRobot; }
      set { _CanMatchRobot = value; }
    }
    private int _IsFailLevelReduce;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"IsFailLevelReduce", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsFailLevelReduce
    {
      get { return _IsFailLevelReduce; }
      set { _IsFailLevelReduce = value; }
    }
    private int _IsPromotion;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"IsPromotion", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsPromotion
    {
      get { return _IsPromotion; }
      set { _IsPromotion = value; }
    }
    private string _PromotionRule;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"PromotionRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PromotionRule
    {
      get { return _PromotionRule; }
      set { _PromotionRule = value; }
    }
    private string _CommonLevelReduce;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"CommonLevelReduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CommonLevelReduce
    {
      get { return _CommonLevelReduce; }
      set { _CommonLevelReduce = value; }
    }
    private int _SeasonStartLevelReduce;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"SeasonStartLevelReduce", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SeasonStartLevelReduce
    {
      get { return _SeasonStartLevelReduce; }
      set { _SeasonStartLevelReduce = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _DailyRewards = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(16, Name=@"DailyRewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DailyRewards
    {
      get { return _DailyRewards; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _SeasonRewards = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(17, Name=@"SeasonRewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> SeasonRewards
    {
      get { return _SeasonRewards; }
    }
  
    private string _Icon;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _SmallIcon;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"SmallIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SmallIcon
    {
      get { return _SmallIcon; }
      set { _SmallIcon = value; }
    }
    private string _SubLevelIcon;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"SubLevelIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SubLevelIcon
    {
      get { return _SubLevelIcon; }
      set { _SubLevelIcon = value; }
    }
    private int _AttrID;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"AttrID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AttrID
    {
      get { return _AttrID; }
      set { _AttrID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eMainLevel")]
    public enum eMainLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bronze", Value=1)]
      Bronze = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Silver", Value=2)]
      Silver = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gold", Value=3)]
      Gold = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Platinum", Value=4)]
      Platinum = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Diamond", Value=5)]
      Diamond = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"King", Value=6)]
      King = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}