//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillTable.proto
// Note: requires additional types generated from: Union.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillTable")]
  public partial class SkillTable : global::ProtoBuf.IExtensible
  {
    public SkillTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _EnglishName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EnglishName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EnglishName
    {
      get { return _EnglishName; }
      set { _EnglishName = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _JobID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"JobID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> JobID
    {
      get { return _JobID; }
    }
  
    private int _Speed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Speed", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Speed
    {
      get { return _Speed; }
      set { _Speed = value; }
    }
    private int _SpeedEffectType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"SpeedEffectType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SpeedEffectType
    {
      get { return _SpeedEffectType; }
      set { _SpeedEffectType = value; }
    }
    private ProtoTable.SkillTable.eSkillType _SkillType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"SkillType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.SkillTable.eSkillType SkillType
    {
      get { return _SkillType; }
      set { _SkillType = value; }
    }
    private int _SkillCategory;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"SkillCategory", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillCategory
    {
      get { return _SkillCategory; }
      set { _SkillCategory = value; }
    }
    private int _IsBuff;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"IsBuff", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsBuff
    {
      get { return _IsBuff; }
      set { _IsBuff = value; }
    }
    private int _IsQTE;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"IsQTE", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsQTE
    {
      get { return _IsQTE; }
      set { _IsQTE = value; }
    }
    private int _SkillPressType;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"SkillPressType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillPressType
    {
      get { return _SkillPressType; }
      set { _SkillPressType = value; }
    }
    private int _WatchBuffID;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"WatchBuffID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WatchBuffID
    {
      get { return _WatchBuffID; }
      set { _WatchBuffID = value; }
    }
    private int _CanUseInPVP;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"CanUseInPVP", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CanUseInPVP
    {
      get { return _CanUseInPVP; }
      set { _CanUseInPVP = value; }
    }
    private int _AttackScalePVP;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"AttackScalePVP", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int AttackScalePVP
    {
      get { return _AttackScalePVP; }
      set { _AttackScalePVP = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.SkillTable.ePreCondition> _PreCondition = new global::System.Collections.Generic.List<ProtoTable.SkillTable.ePreCondition>();
    [global::ProtoBuf.ProtoMember(16, Name=@"PreCondition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoTable.SkillTable.ePreCondition> PreCondition
    {
      get { return _PreCondition; }
    }
  
    private ProtoTable.UnionCell _Probability;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"Probability", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell Probability
    {
      get { return _Probability; }
      set { _Probability = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _HitEffectIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"HitEffectIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> HitEffectIDs
    {
      get { return _HitEffectIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BuffInfoIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"BuffInfoIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BuffInfoIDs
    {
      get { return _BuffInfoIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _MechismIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"MechismIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> MechismIDs
    {
      get { return _MechismIDs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _InterruptSkills = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"InterruptSkills", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> InterruptSkills
    {
      get { return _InterruptSkills; }
    }
  
    private bool _IsForce;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"IsForce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsForce
    {
      get { return _IsForce; }
      set { _IsForce = value; }
    }
    private bool _IsCanCancel;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"IsCanCancel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsCanCancel
    {
      get { return _IsCanCancel; }
      set { _IsCanCancel = value; }
    }
    private bool _IsCanDispose;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"IsCanDispose", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsCanDispose
    {
      get { return _IsCanDispose; }
      set { _IsCanDispose = value; }
    }
    private bool _IsChargeEnable;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"IsChargeEnable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsChargeEnable
    {
      get { return _IsChargeEnable; }
      set { _IsChargeEnable = value; }
    }
    private bool _IsWalkEnable;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"IsWalkEnable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsWalkEnable
    {
      get { return _IsWalkEnable; }
      set { _IsWalkEnable = value; }
    }
    private int _WalkMode;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"WalkMode", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WalkMode
    {
      get { return _WalkMode; }
      set { _WalkMode = value; }
    }
    private ProtoTable.UnionCell _WalkSpeed;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"WalkSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell WalkSpeed
    {
      get { return _WalkSpeed; }
      set { _WalkSpeed = value; }
    }
    private int _SummonRestrainEffectID;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"SummonRestrainEffectID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SummonRestrainEffectID
    {
      get { return _SummonRestrainEffectID; }
      set { _SummonRestrainEffectID = value; }
    }
    private int _CostMode;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"CostMode", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CostMode
    {
      get { return _CostMode; }
      set { _CostMode = value; }
    }
    private ProtoTable.UnionCell _HPCostPercent;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"HPCostPercent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HPCostPercent
    {
      get { return _HPCostPercent; }
      set { _HPCostPercent = value; }
    }
    private ProtoTable.UnionCell _HPCost;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"HPCost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell HPCost
    {
      get { return _HPCost; }
      set { _HPCost = value; }
    }
    private ProtoTable.UnionCell _MPCost;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"MPCost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell MPCost
    {
      get { return _MPCost; }
      set { _MPCost = value; }
    }
    private ProtoTable.UnionCell _CrystalCost;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"CrystalCost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell CrystalCost
    {
      get { return _CrystalCost; }
      set { _CrystalCost = value; }
    }
    private int _SpellTime;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"SpellTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SpellTime
    {
      get { return _SpellTime; }
      set { _SpellTime = value; }
    }
    private int _SpellTimePVP;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"SpellTimePVP", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SpellTimePVP
    {
      get { return _SpellTimePVP; }
      set { _SpellTimePVP = value; }
    }
    private ProtoTable.UnionCell _RefreshTime;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"RefreshTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell RefreshTime
    {
      get { return _RefreshTime; }
      set { _RefreshTime = value; }
    }
    private ProtoTable.UnionCell _InitCD;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"InitCD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell InitCD
    {
      get { return _InitCD; }
      set { _InitCD = value; }
    }
    private ProtoTable.UnionCell _RefreshTimePVP;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"RefreshTimePVP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell RefreshTimePVP
    {
      get { return _RefreshTimePVP; }
      set { _RefreshTimePVP = value; }
    }
    private ProtoTable.UnionCell _InitCDPVP;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"InitCDPVP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell InitCDPVP
    {
      get { return _InitCDPVP; }
      set { _InitCDPVP = value; }
    }
    private ProtoTable.SkillTable.eSkillTarget _SkillTarget;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"SkillTarget", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.SkillTable.eSkillTarget SkillTarget
    {
      get { return _SkillTarget; }
      set { _SkillTarget = value; }
    }
    private int _IsStudy;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"IsStudy", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int IsStudy
    {
      get { return _IsStudy; }
      set { _IsStudy = value; }
    }
    private int _LevelLimit;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private int _LevelLimitAmend;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"LevelLimitAmend", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LevelLimitAmend
    {
      get { return _LevelLimitAmend; }
      set { _LevelLimitAmend = value; }
    }
    private int _TopLevelLimit;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"TopLevelLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TopLevelLimit
    {
      get { return _TopLevelLimit; }
      set { _TopLevelLimit = value; }
    }
    private int _TopLevel;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"TopLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TopLevel
    {
      get { return _TopLevel; }
      set { _TopLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _PreSkills = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(47, Name=@"PreSkills", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PreSkills
    {
      get { return _PreSkills; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PreSkillsLevel = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(48, Name=@"PreSkillsLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PreSkillsLevel
    {
      get { return _PreSkillsLevel; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PostSkills = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(49, Name=@"PostSkills", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PostSkills
    {
      get { return _PostSkills; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _NeedLevel = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(50, Name=@"NeedLevel", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> NeedLevel
    {
      get { return _NeedLevel; }
    }
  
    private int _LearnSPCost;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"LearnSPCost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LearnSPCost
    {
      get { return _LearnSPCost; }
      set { _LearnSPCost = value; }
    }
    private int _LearnGoodCost;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"LearnGoodCost", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LearnGoodCost
    {
      get { return _LearnGoodCost; }
      set { _LearnGoodCost = value; }
    }
    private int _BindButtonIndex;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"BindButtonIndex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BindButtonIndex
    {
      get { return _BindButtonIndex; }
      set { _BindButtonIndex = value; }
    }
    private string _SkillSpeech;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"SkillSpeech", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillSpeech
    {
      get { return _SkillSpeech; }
      set { _SkillSpeech = value; }
    }
    private int _SkillSpeechRand;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"SkillSpeechRand", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillSpeechRand
    {
      get { return _SkillSpeechRand; }
      set { _SkillSpeechRand = value; }
    }
    private string _SkillDealText;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"SkillDealText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillDealText
    {
      get { return _SkillDealText; }
      set { _SkillDealText = value; }
    }
    private int _SkillDealTextDuration;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"SkillDealTextDuration", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillDealTextDuration
    {
      get { return _SkillDealTextDuration; }
      set { _SkillDealTextDuration = value; }
    }
    private int _SwitchSkillID;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"SwitchSkillID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SwitchSkillID
    {
      get { return _SwitchSkillID; }
      set { _SwitchSkillID = value; }
    }
    private int _RangeX;
    [global::ProtoBuf.ProtoMember(59, IsRequired = true, Name=@"RangeX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RangeX
    {
      get { return _RangeX; }
      set { _RangeX = value; }
    }
    private int _RangeY;
    [global::ProtoBuf.ProtoMember(60, IsRequired = true, Name=@"RangeY", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RangeY
    {
      get { return _RangeY; }
      set { _RangeY = value; }
    }
    private int _BackRangeX;
    [global::ProtoBuf.ProtoMember(61, IsRequired = true, Name=@"BackRangeX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BackRangeX
    {
      get { return _BackRangeX; }
      set { _BackRangeX = value; }
    }
    private int _Weight;
    [global::ProtoBuf.ProtoMember(62, IsRequired = true, Name=@"Weight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Weight
    {
      get { return _Weight; }
      set { _Weight = value; }
    }
    private string _AttackInfo;
    [global::ProtoBuf.ProtoMember(63, IsRequired = true, Name=@"AttackInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttackInfo
    {
      get { return _AttackInfo; }
      set { _AttackInfo = value; }
    }
    private ProtoTable.UnionCell _Zscale;
    [global::ProtoBuf.ProtoMember(64, IsRequired = true, Name=@"Zscale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell Zscale
    {
      get { return _Zscale; }
      set { _Zscale = value; }
    }
    private ProtoTable.UnionCell _PVPZscale;
    [global::ProtoBuf.ProtoMember(65, IsRequired = true, Name=@"PVPZscale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell PVPZscale
    {
      get { return _PVPZscale; }
      set { _PVPZscale = value; }
    }
    private int _SkillOperation;
    [global::ProtoBuf.ProtoMember(66, IsRequired = true, Name=@"SkillOperation", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillOperation
    {
      get { return _SkillOperation; }
      set { _SkillOperation = value; }
    }
    private int _SkillOpTarget;
    [global::ProtoBuf.ProtoMember(67, IsRequired = true, Name=@"SkillOpTarget", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SkillOpTarget
    {
      get { return _SkillOpTarget; }
      set { _SkillOpTarget = value; }
    }
    private string _SkillOpVar;
    [global::ProtoBuf.ProtoMember(68, IsRequired = true, Name=@"SkillOpVar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillOpVar
    {
      get { return _SkillOpVar; }
      set { _SkillOpVar = value; }
    }
    private ProtoTable.UnionCell _SkillOpValue;
    [global::ProtoBuf.ProtoMember(69, IsRequired = true, Name=@"SkillOpValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoTable.UnionCell SkillOpValue
    {
      get { return _SkillOpValue; }
      set { _SkillOpValue = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _SkillOpSkillIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(70, Name=@"SkillOpSkillIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> SkillOpSkillIDs
    {
      get { return _SkillOpSkillIDs; }
    }
  
    private string _DescriptionA;
    [global::ProtoBuf.ProtoMember(71, IsRequired = true, Name=@"DescriptionA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionA
    {
      get { return _DescriptionA; }
      set { _DescriptionA = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueA = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(72, Name=@"ValueA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueA
    {
      get { return _ValueA; }
    }
  
    private string _DescriptionB;
    [global::ProtoBuf.ProtoMember(73, IsRequired = true, Name=@"DescriptionB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionB
    {
      get { return _DescriptionB; }
      set { _DescriptionB = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueB = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(74, Name=@"ValueB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueB
    {
      get { return _ValueB; }
    }
  
    private string _DescriptionC;
    [global::ProtoBuf.ProtoMember(75, IsRequired = true, Name=@"DescriptionC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionC
    {
      get { return _DescriptionC; }
      set { _DescriptionC = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueC = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(76, Name=@"ValueC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueC
    {
      get { return _ValueC; }
    }
  
    private string _DescriptionD;
    [global::ProtoBuf.ProtoMember(77, IsRequired = true, Name=@"DescriptionD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionD
    {
      get { return _DescriptionD; }
      set { _DescriptionD = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueD = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(78, Name=@"ValueD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueD
    {
      get { return _ValueD; }
    }
  
    private string _DescriptionE;
    [global::ProtoBuf.ProtoMember(79, IsRequired = true, Name=@"DescriptionE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionE
    {
      get { return _DescriptionE; }
      set { _DescriptionE = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueE = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(80, Name=@"ValueE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueE
    {
      get { return _ValueE; }
    }
  
    private string _DescriptionF;
    [global::ProtoBuf.ProtoMember(81, IsRequired = true, Name=@"DescriptionF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionF
    {
      get { return _DescriptionF; }
      set { _DescriptionF = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueF = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(82, Name=@"ValueF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueF
    {
      get { return _ValueF; }
    }
  
    private string _DescriptionG;
    [global::ProtoBuf.ProtoMember(83, IsRequired = true, Name=@"DescriptionG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DescriptionG
    {
      get { return _DescriptionG; }
      set { _DescriptionG = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoTable.UnionCell> _ValueG = new global::System.Collections.Generic.List<ProtoTable.UnionCell>();
    [global::ProtoBuf.ProtoMember(84, Name=@"ValueG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoTable.UnionCell> ValueG
    {
      get { return _ValueG; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSkillType")]
    public enum eSkillType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVE", Value=1)]
      ACTIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSIVE", Value=2)]
      PASSIVE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ePreCondition")]
    public enum ePreCondition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAND", Value=1)]
      STAND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALK", Value=2)]
      WALK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUN", Value=3)]
      RUN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JUMP", Value=4)]
      JUMP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BEHIT", Value=5)]
      BEHIT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTERSCENE", Value=6)]
      ENTERSCENE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INIT", Value=7)]
      INIT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOWHP", Value=8)]
      LOWHP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAODI", Value=9)]
      DAODI = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSkillTarget")]
    public enum eSkillTarget
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIENDLY", Value=1)]
      FRIENDLY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENEMY", Value=2)]
      ENEMY = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}