//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ActivityDungeonTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityDungeonTable")]
  public partial class ActivityDungeonTable : global::ProtoBuf.IExtensible
  {
    public ActivityDungeonTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ActivityID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ActivityID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ActivityID
    {
      get { return _ActivityID; }
    }
  
    private string _ImagePath;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ImagePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ImagePath
    {
      get { return _ImagePath; }
      set { _ImagePath = value; }
    }
    private string _OpenTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"OpenTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OpenTime
    {
      get { return _OpenTime; }
      set { _OpenTime = value; }
    }
    private bool _ShowModeFlag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ShowModeFlag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ShowModeFlag
    {
      get { return _ShowModeFlag; }
      set { _ShowModeFlag = value; }
    }
    private string _ModeBoardPath;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ModeBoardPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ModeBoardPath
    {
      get { return _ModeBoardPath; }
      set { _ModeBoardPath = value; }
    }
    private string _ModeIconPath;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ModeIconPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ModeIconPath
    {
      get { return _ModeIconPath; }
      set { _ModeIconPath = value; }
    }
    private string _Mode;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Mode
    {
      get { return _Mode; }
      set { _Mode = value; }
    }
    private ProtoTable.ActivityDungeonTable.eActivityType _ActivityType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"ActivityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ActivityDungeonTable.eActivityType ActivityType
    {
      get { return _ActivityType; }
      set { _ActivityType = value; }
    }
    private string _ActivityTypeDesc;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ActivityTypeDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActivityTypeDesc
    {
      get { return _ActivityTypeDesc; }
      set { _ActivityTypeDesc = value; }
    }
    private string _SingleTabIcon;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"SingleTabIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SingleTabIcon
    {
      get { return _SingleTabIcon; }
      set { _SingleTabIcon = value; }
    }
    private int _DungeonID;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"DungeonID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DungeonID
    {
      get { return _DungeonID; }
      set { _DungeonID = value; }
    }
    private string _CollectDataPath;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"CollectDataPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CollectDataPath
    {
      get { return _CollectDataPath; }
      set { _CollectDataPath = value; }
    }
    private bool _ShowCount;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"ShowCount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ShowCount
    {
      get { return _ShowCount; }
      set { _ShowCount = value; }
    }
    private string _ShowCountDesc;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"ShowCountDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ShowCountDesc
    {
      get { return _ShowCountDesc; }
      set { _ShowCountDesc = value; }
    }
    private ProtoTable.ActivityDungeonTable.eDropType _DropType;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"DropType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ActivityDungeonTable.eDropType DropType
    {
      get { return _DropType; }
      set { _DropType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _DropItems = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"DropItems", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> DropItems
    {
      get { return _DropItems; }
    }
  
    private int _TabPriority;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"TabPriority", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int TabPriority
    {
      get { return _TabPriority; }
      set { _TabPriority = value; }
    }
    private string _TabName;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"TabName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TabName
    {
      get { return _TabName; }
      set { _TabName = value; }
    }
    private int _SubPriority;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"SubPriority", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SubPriority
    {
      get { return _SubPriority; }
      set { _SubPriority = value; }
    }
    private ProtoTable.ActivityDungeonTable.eSubItemOpenType _SubItemOpenType;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"SubItemOpenType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ActivityDungeonTable.eSubItemOpenType SubItemOpenType
    {
      get { return _SubItemOpenType; }
      set { _SubItemOpenType = value; }
    }
    private ProtoTable.ActivityDungeonTable.eSubNameType _SubNameType;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"SubNameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ActivityDungeonTable.eSubNameType SubNameType
    {
      get { return _SubNameType; }
      set { _SubNameType = value; }
    }
    private string _SubName;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"SubName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SubName
    {
      get { return _SubName; }
      set { _SubName = value; }
    }
    private ProtoTable.ActivityDungeonTable.eDescriptionType _DescriptionType;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"DescriptionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ActivityDungeonTable.eDescriptionType DescriptionType
    {
      get { return _DescriptionType; }
      set { _DescriptionType = value; }
    }
    private string _Description;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _ExtraDescription;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"ExtraDescription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ExtraDescription
    {
      get { return _ExtraDescription; }
      set { _ExtraDescription = value; }
    }
    private string _PlayDescription;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"PlayDescription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayDescription
    {
      get { return _PlayDescription; }
      set { _PlayDescription = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eActivityType")]
    public enum eActivityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TimeLimit", Value=1)]
      TimeLimit = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Daily", Value=2)]
      Daily = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Reward", Value=3)]
      Reward = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDropType")]
    public enum eDropType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DungeonDrop", Value=1)]
      DungeonDrop = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CustomDrop", Value=2)]
      CustomDrop = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSubItemOpenType")]
    public enum eSubItemOpenType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DungeonFrame", Value=1)]
      DungeonFrame = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CommonFrame", Value=2)]
      CommonFrame = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSubNameType")]
    public enum eSubNameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DungeonName", Value=1)]
      DungeonName = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CustomName", Value=2)]
      CustomName = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eDescriptionType")]
    public enum eDescriptionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DungeonDescription", Value=1)]
      DungeonDescription = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CustomDescription", Value=2)]
      CustomDescription = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}