//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AreaTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AreaTable")]
  public partial class AreaTable : global::ProtoBuf.IExtensible
  {
    public AreaTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _MainlandID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MainlandID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MainlandID
    {
      get { return _MainlandID; }
      set { _MainlandID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _TownIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"TownIDs", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> TownIDs
    {
      get { return _TownIDs; }
    }
  
    private string _LoadBG;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LoadBG", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoadBG
    {
      get { return _LoadBG; }
      set { _LoadBG = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}