//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CommonTipsDesc.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonTipsDesc")]
  public partial class CommonTipsDesc : global::ProtoBuf.IExtensible
  {
    public CommonTipsDesc() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Descs;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Descs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Descs
    {
      get { return _Descs; }
      set { _Descs = value; }
    }
    private ProtoTable.CommonTipsDesc.eShowType _ShowType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ShowType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.CommonTipsDesc.eShowType ShowType
    {
      get { return _ShowType; }
      set { _ShowType = value; }
    }
    private ProtoTable.CommonTipsDesc.eShowMode _ShowMode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ShowMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.CommonTipsDesc.eShowMode ShowMode
    {
      get { return _ShowMode; }
      set { _ShowMode = value; }
    }
    private string _TitleText;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TitleText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TitleText
    {
      get { return _TitleText; }
      set { _TitleText = value; }
    }
    private string _ButtonText;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ButtonText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ButtonText
    {
      get { return _ButtonText; }
      set { _ButtonText = value; }
    }
    private string _CancelBtnText;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"CancelBtnText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CancelBtnText
    {
      get { return _CancelBtnText; }
      set { _CancelBtnText = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eShowType")]
    public enum eShowType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_MSG_BOX_OK", Value=1)]
      CT_MSG_BOX_OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_MSG_BOX_OK_CANCEL", Value=2)]
      CT_MSG_BOX_OK_CANCEL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_MSG_BOX_CANCEL_OK", Value=3)]
      CT_MSG_BOX_CANCEL_OK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_CLICK_CONFIRM_FRAME", Value=10)]
      CT_CLICK_CONFIRM_FRAME = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SYSTEM_TEXT_ANIMATION", Value=20)]
      CT_SYSTEM_TEXT_ANIMATION = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_TEXT_FLOAT_EFFECT", Value=21)]
      CT_TEXT_FLOAT_EFFECT = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SCROLL_LIGHT", Value=100)]
      CT_SCROLL_LIGHT = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_DUNGEON_TEXT_ANIMATION", Value=40)]
      CT_DUNGEON_TEXT_ANIMATION = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_DUNGEON_TEXT_ANIMATION_2", Value=41)]
      CT_DUNGEON_TEXT_ANIMATION_2 = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_HOT_UPDATE_OK", Value=101)]
      CT_HOT_UPDATE_OK = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_HOT_UPDATE_OK_CANCEL", Value=102)]
      CT_HOT_UPDATE_OK_CANCEL = 102
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eShowMode")]
    public enum eShowMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SI_NULL", Value=0)]
      SI_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SI_UNIQUE", Value=1)]
      SI_UNIQUE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SI_IMMEDIATELY", Value=2)]
      SI_IMMEDIATELY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SI_QUEUE", Value=3)]
      SI_QUEUE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}