//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DungeonPrefixLimitTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonPrefixLimitTable")]
  public partial class DungeonPrefixLimitTable : global::ProtoBuf.IExtensible
  {
    public DungeonPrefixLimitTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Hard;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Hard", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Hard
    {
      get { return _Hard; }
      set { _Hard = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _TotalNum = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"TotalNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> TotalNum
    {
      get { return _TotalNum; }
    }
  
    private int _SeniorPrefixNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SeniorPrefixNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SeniorPrefixNum
    {
      get { return _SeniorPrefixNum; }
      set { _SeniorPrefixNum = value; }
    }
    private int _LowPrefixNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"LowPrefixNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LowPrefixNum
    {
      get { return _LowPrefixNum; }
      set { _LowPrefixNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}