//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EnergyStone.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnergyStone")]
  public partial class EnergyStone : global::ProtoBuf.IExtensible
  {
    public EnergyStone() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _EnergyValue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EnergyValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int EnergyValue
    {
      get { return _EnergyValue; }
      set { _EnergyValue = value; }
    }
    private ProtoTable.EnergyStone.eType _Type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.EnergyStone.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _ItemID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RED", Value=1)]
      RED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREEN", Value=2)]
      GREEN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YELLOW", Value=3)]
      YELLOW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUE", Value=4)]
      BLUE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACK", Value=5)]
      BLACK = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COLORLESS", Value=6)]
      COLORLESS = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}