//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipStrColorRatioTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipStrColorRatioTable")]
  public partial class EquipStrColorRatioTable : global::ProtoBuf.IExtensible
  {
    public EquipStrColorRatioTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Lv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _WhiteRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"WhiteRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> WhiteRatio
    {
      get { return _WhiteRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BlueRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"BlueRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BlueRatio
    {
      get { return _BlueRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PurpleRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"PurpleRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PurpleRatio
    {
      get { return _PurpleRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _GreenRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"GreenRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> GreenRatio
    {
      get { return _GreenRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PinkRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"PinkRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PinkRatio
    {
      get { return _PinkRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _YellowRatio = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"YellowRatio", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> YellowRatio
    {
      get { return _YellowRatio; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}