//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuidanceEntranceTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuidanceEntranceTable")]
  public partial class GuidanceEntranceTable : global::ProtoBuf.IExtensible
  {
    public GuidanceEntranceTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _FunctionId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"FunctionId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int FunctionId
    {
      get { return _FunctionId; }
      set { _FunctionId = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _LinkInfo;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LinkInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LinkInfo
    {
      get { return _LinkInfo; }
      set { _LinkInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}