//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoadingResourcesTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadingResourcesTable")]
  public partial class LoadingResourcesTable : global::ProtoBuf.IExtensible
  {
    public LoadingResourcesTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private ProtoTable.LoadingResourcesTable.eType _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.LoadingResourcesTable.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private string _Resources;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Resources", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Resources
    {
      get { return _Resources; }
      set { _Resources = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AT_NONE", Value=0)]
      AT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AT_EQUIP", Value=1)]
      AT_EQUIP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AT_DEFENCE", Value=2)]
      AT_DEFENCE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}