//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MagicCardTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MagicCardTable")]
  public partial class MagicCardTable : global::ProtoBuf.IExtensible
  {
    public MagicCardTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Color", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Color
    {
      get { return _Color; }
      set { _Color = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Parts = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Parts", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Parts
    {
      get { return _Parts; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PropType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"PropType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PropType
    {
      get { return _PropType; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PropValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"PropValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PropValue
    {
      get { return _PropValue; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BuffID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"BuffID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BuffID
    {
      get { return _BuffID; }
    }
  
    private int _Weight;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Weight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Weight
    {
      get { return _Weight; }
      set { _Weight = value; }
    }
    private int _Rate;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Rate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Rate
    {
      get { return _Rate; }
      set { _Rate = value; }
    }
    private string _SkillAttributes;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"SkillAttributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillAttributes
    {
      get { return _SkillAttributes; }
      set { _SkillAttributes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}