//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RandPropValueTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandPropValueTable")]
  public partial class RandPropValueTable : global::ProtoBuf.IExtensible
  {
    public RandPropValueTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private ProtoTable.RandPropValueTable.eRandType _RandType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RandType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.RandPropValueTable.eRandType RandType
    {
      get { return _RandType; }
      set { _RandType = value; }
    }
    private ProtoTable.RandPropValueTable.eColor _Color;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.RandPropValueTable.eColor Color
    {
      get { return _Color; }
      set { _Color = value; }
    }
    private int _LevelMin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LevelMin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LevelMin
    {
      get { return _LevelMin; }
      set { _LevelMin = value; }
    }
    private int _LevelMax;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LevelMax", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int LevelMax
    {
      get { return _LevelMax; }
      set { _LevelMax = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Value = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Value
    {
      get { return _Value; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Weight = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"Weight", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> Weight
    {
      get { return _Weight; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eRandType")]
    public enum eRandType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STR", Value=1)]
      STR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STA", Value=2)]
      STA = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INT", Value=3)]
      INT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPR", Value=4)]
      SPR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HPMAX", Value=5)]
      HPMAX = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MPMAX", Value=6)]
      MPMAX = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HPREC", Value=7)]
      HPREC = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MPREC", Value=8)]
      MPREC = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIT", Value=9)]
      HIT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEX", Value=10)]
      DEX = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYCRT", Value=11)]
      PHYCRT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MGCCRT", Value=12)]
      MGCCRT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATKSPD", Value=13)]
      ATKSPD = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RDYSPD", Value=14)]
      RDYSPD = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVSPD", Value=15)]
      MOVSPD = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JUMP", Value=16)]
      JUMP = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HITREC", Value=17)]
      HITREC = 17
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eColor")]
    public enum eColor
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WHITE", Value=1)]
      WHITE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUE", Value=2)]
      BLUE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURPLE", Value=3)]
      PURPLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREEN", Value=4)]
      GREEN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINK", Value=5)]
      PINK = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YELLOW", Value=6)]
      YELLOW = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}