//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResTable")]
  public partial class ResTable : global::ProtoBuf.IExtensible
  {
    public ResTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private ProtoTable.ResTable.eType _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ResTable.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _IconPath;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"IconPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IconPath
    {
      get { return _IconPath; }
      set { _IconPath = value; }
    }
    private string _ParentName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ParentName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ParentName
    {
      get { return _ParentName; }
      set { _ParentName = value; }
    }
    private string _ModelPath;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ModelPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ModelPath
    {
      get { return _ModelPath; }
      set { _ModelPath = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _ActionConfigPath = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ActionConfigPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ActionConfigPath
    {
      get { return _ActionConfigPath; }
    }
  
    private string _ActionConfigPath2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ActionConfigPath2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActionConfigPath2
    {
      get { return _ActionConfigPath2; }
      set { _ActionConfigPath2 = value; }
    }
    private int _WeaponHitSFX;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"WeaponHitSFX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int WeaponHitSFX
    {
      get { return _WeaponHitSFX; }
      set { _WeaponHitSFX = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTOR", Value=1)]
      ACTOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY", Value=2)]
      ENTITY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DESTROYABLE", Value=3)]
      DESTROYABLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DECORATOR", Value=4)]
      DECORATOR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP", Value=5)]
      EQUIP = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}