//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RobotConfigTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotConfigTable")]
  public partial class RobotConfigTable : global::ProtoBuf.IExtensible
  {
    public RobotConfigTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Occu;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Occu", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Occu
    {
      get { return _Occu; }
      set { _Occu = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Skills = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Skills
    {
      get { return _Skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}