//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillDescriptionTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillDescriptionTable")]
  public partial class SkillDescriptionTable : global::ProtoBuf.IExtensible
  {
    public SkillDescriptionTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Description;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private string _DataText1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DataText1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText1
    {
      get { return _DataText1; }
      set { _DataText1 = value; }
    }
    private string _DataNumber1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DataNumber1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber1
    {
      get { return _DataNumber1; }
      set { _DataNumber1 = value; }
    }
    private string _PVPDataNum1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PVPDataNum1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum1
    {
      get { return _PVPDataNum1; }
      set { _PVPDataNum1 = value; }
    }
    private string _DataText2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"DataText2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText2
    {
      get { return _DataText2; }
      set { _DataText2 = value; }
    }
    private string _DataNumber2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"DataNumber2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber2
    {
      get { return _DataNumber2; }
      set { _DataNumber2 = value; }
    }
    private string _PVPDataNum2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"PVPDataNum2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum2
    {
      get { return _PVPDataNum2; }
      set { _PVPDataNum2 = value; }
    }
    private string _DataText3;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"DataText3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText3
    {
      get { return _DataText3; }
      set { _DataText3 = value; }
    }
    private string _DataNumber3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"DataNumber3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber3
    {
      get { return _DataNumber3; }
      set { _DataNumber3 = value; }
    }
    private string _PVPDataNum3;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"PVPDataNum3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum3
    {
      get { return _PVPDataNum3; }
      set { _PVPDataNum3 = value; }
    }
    private string _DataText4;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"DataText4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText4
    {
      get { return _DataText4; }
      set { _DataText4 = value; }
    }
    private string _DataNumber4;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"DataNumber4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber4
    {
      get { return _DataNumber4; }
      set { _DataNumber4 = value; }
    }
    private string _PVPDataNum4;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"PVPDataNum4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum4
    {
      get { return _PVPDataNum4; }
      set { _PVPDataNum4 = value; }
    }
    private string _DataText5;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"DataText5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText5
    {
      get { return _DataText5; }
      set { _DataText5 = value; }
    }
    private string _DataNumber5;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"DataNumber5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber5
    {
      get { return _DataNumber5; }
      set { _DataNumber5 = value; }
    }
    private string _PVPDataNum5;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"PVPDataNum5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum5
    {
      get { return _PVPDataNum5; }
      set { _PVPDataNum5 = value; }
    }
    private string _DataText6;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"DataText6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText6
    {
      get { return _DataText6; }
      set { _DataText6 = value; }
    }
    private string _DataNumber6;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"DataNumber6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber6
    {
      get { return _DataNumber6; }
      set { _DataNumber6 = value; }
    }
    private string _PVPDataNum6;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PVPDataNum6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum6
    {
      get { return _PVPDataNum6; }
      set { _PVPDataNum6 = value; }
    }
    private string _DataText7;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"DataText7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText7
    {
      get { return _DataText7; }
      set { _DataText7 = value; }
    }
    private string _DataNumber7;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"DataNumber7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber7
    {
      get { return _DataNumber7; }
      set { _DataNumber7 = value; }
    }
    private string _PVPDataNum7;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"PVPDataNum7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum7
    {
      get { return _PVPDataNum7; }
      set { _PVPDataNum7 = value; }
    }
    private string _DataText8;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"DataText8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText8
    {
      get { return _DataText8; }
      set { _DataText8 = value; }
    }
    private string _DataNumber8;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"DataNumber8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber8
    {
      get { return _DataNumber8; }
      set { _DataNumber8 = value; }
    }
    private string _PVPDataNum8;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"PVPDataNum8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum8
    {
      get { return _PVPDataNum8; }
      set { _PVPDataNum8 = value; }
    }
    private string _DataText9;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"DataText9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText9
    {
      get { return _DataText9; }
      set { _DataText9 = value; }
    }
    private string _DataNumber9;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"DataNumber9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber9
    {
      get { return _DataNumber9; }
      set { _DataNumber9 = value; }
    }
    private string _PVPDataNum9;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"PVPDataNum9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum9
    {
      get { return _PVPDataNum9; }
      set { _PVPDataNum9 = value; }
    }
    private string _DataText10;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"DataText10", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText10
    {
      get { return _DataText10; }
      set { _DataText10 = value; }
    }
    private string _DataNumber10;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"DataNumber10", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber10
    {
      get { return _DataNumber10; }
      set { _DataNumber10 = value; }
    }
    private string _PVPDataNum10;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"PVPDataNum10", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum10
    {
      get { return _PVPDataNum10; }
      set { _PVPDataNum10 = value; }
    }
    private string _DataText11;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"DataText11", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText11
    {
      get { return _DataText11; }
      set { _DataText11 = value; }
    }
    private string _DataNumber11;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"DataNumber11", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber11
    {
      get { return _DataNumber11; }
      set { _DataNumber11 = value; }
    }
    private string _PVPDataNum11;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"PVPDataNum11", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum11
    {
      get { return _PVPDataNum11; }
      set { _PVPDataNum11 = value; }
    }
    private string _DataText12;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"DataText12", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataText12
    {
      get { return _DataText12; }
      set { _DataText12 = value; }
    }
    private string _DataNumber12;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"DataNumber12", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DataNumber12
    {
      get { return _DataNumber12; }
      set { _DataNumber12 = value; }
    }
    private string _PVPDataNum12;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"PVPDataNum12", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PVPDataNum12
    {
      get { return _PVPDataNum12; }
      set { _PVPDataNum12 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}