//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TeamRewardTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamRewardTable")]
  public partial class TeamRewardTable : global::ProtoBuf.IExtensible
  {
    public TeamRewardTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Reward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Reward", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Reward
    {
      get { return _Reward; }
      set { _Reward = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private int _Prob;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Prob", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Prob
    {
      get { return _Prob; }
      set { _Prob = value; }
    }
    private int _DailyLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"DailyLimit", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DailyLimit
    {
      get { return _DailyLimit; }
      set { _DailyLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}