//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LogItem.proto
// Note: requires additional types generated from: MsgHead.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogItem")]
  public partial class LogItem : global::ProtoBuf.IExtensible
  {
    public LogItem() {}
    
    private Protocol.MsgID _id = Protocol.MsgID.MID_LOG;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Protocol.MsgID.MID_LOG)]
    public Protocol.MsgID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _subId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int subId
    {
      get { return _subId; }
      set { _subId = value; }
    }
    private int _logId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"logId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int logId
    {
      get { return _logId; }
      set { _logId = value; }
    }
    private string _logValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"logValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string logValue
    {
      get { return _logValue; }
      set { _logValue = value; }
    }
    private Protocol.LogItem.LogType _eLogType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"eLogType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Protocol.LogItem.LogType eLogType
    {
      get { return _eLogType; }
      set { _eLogType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LogType")]
    public enum LogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT_NORMAL", Value=1)]
      LT_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT_WARNING", Value=2)]
      LT_WARNING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT_ERROR", Value=4)]
      LT_ERROR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT_PROCESS", Value=8)]
      LT_PROCESS = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}